export const API_ROUTES = {
  config: '/api/config',
  csrfToken: '/api/csrf-token',
  health: '/api/health',
  avatarBase: '/api/avatar',
  avatar: (name: string) => `/api/avatar?name=${encodeURIComponent(name)}`,
  canvases: {
    base: '/api/canvases',
    sync: '/api/canvases/sync',
    byId: (uuid: string) => `/api/canvases/${encodeURIComponent(uuid)}`,
  },
  chat: '/api/chat',
  auth: {
    forgotPassword: '/api/forgot-password',
    google: '/api/auth/google',
    googleCallback: '/api/auth/google/callback',
    googleLink: '/api/auth/google/link',
    googleVerify: '/api/auth/google/verify',
    login: '/api/login',
    login2fa: '/api/login/verify-2fa',
    logout: '/api/logout',
    logoutAll: '/api/auth/logout-all',
    me: '/api/me',
    registerResendCode: '/api/register/resend-code',
    registerSendCode: '/api/register/send-code',
    registerStage1: '/api/register/stage1-validate',
    registerVerifyCode: '/api/register/verify-code',
    resetPassword: '/api/reset-password',
    resetPasswordValidate: (token: string) => `/api/reset-password/validate?token=${encodeURIComponent(token)}`,
    switchAccount: '/api/auth/switch-account',
  },
  settings: {
    accountDelete: '/api/settings/account/delete',
    avatar: '/api/settings/avatar',
    email: '/api/settings/email',
    emailRequestCode: '/api/settings/email/request-code',
    emailVerifyCode: '/api/settings/email/verify-code',
    googleUnlink: '/api/settings/google/unlink',
    password: '/api/settings/password',
    passwordStatus: '/api/settings/password/status',
    passwordVerify: '/api/settings/password/verify',
    preferences: '/api/settings/preferences',
    twoFactorDisable: '/api/settings/2fa/disable',
    twoFactorEnable: '/api/settings/2fa/enable',
    twoFactorGenerate: '/api/settings/2fa/generate',
    twoFactorStatus: '/api/settings/2fa/status',
    username: '/api/settings/username',
  },
  subscriptions: {
    autoRenewal: '/api/subscriptions/auto-renewal',
    base: '/api/subscriptions',
    cancelImmediate: '/api/subscriptions/cancel-immediate',
    checkout: '/api/subscriptions/checkout',
    details: '/api/subscriptions/details',
    history: '/api/subscriptions/history',
    paymentMethodDefault: (pmId: string) => `/api/subscriptions/payment-methods/${encodeURIComponent(pmId)}/default`,
    paymentMethodDelete: (pmId: string) => `/api/subscriptions/payment-methods/${encodeURIComponent(pmId)}`,
    paymentMethods: '/api/subscriptions/payment-methods',
    setupIntent: '/api/subscriptions/setup-intent',
    verifySession: (sessionId: string) => `/api/subscriptions/verify-session?session_id=${encodeURIComponent(sessionId)}`,
  },
  telemetry: {
    events: '/api/telemetry/events',
    stats: '/api/telemetry/stats',
    vitals: '/api/telemetry/vitals',
  },
} as const;

export default API_ROUTES;
