import { BoardElement } from '../views/board/board.types.js';

export function getBoardTemplateElements(templateId?: string | null): BoardElement[] {
  if (!templateId) return [];

  const uid = (prefix: string) => `${prefix}_${Math.random().toString(36).substring(2, 9)}`;

  switch (templateId) {
    case 'tmpl-board-brainstorm':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '💡 Lluvia de Ideas y Notas Rápidas',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        {
          color: '#fef08a',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Nueva funcionalidad:\nLienzo visual blanco para máxima concentración.',
          textColor: '#713f12',
          type: 'sticky',
          width: 150,
          x: 100,
          y: 110,
        },
        {
          color: '#bae6fd',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Optimización de UX:\nAtajos de teclado intuitivos y herramientas rápidas.',
          textColor: '#0369a1',
          type: 'sticky',
          width: 150,
          x: 280,
          y: 110,
        },
        {
          color: '#bbf7d0',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Colaboración en vivo:\nCursores de equipo con colores diferenciados.',
          textColor: '#15803d',
          type: 'sticky',
          width: 150,
          x: 460,
          y: 110,
        },
        {
          color: '#fbcfe8',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Plantillas prediseñadas:\n10 plantillas limpias por cada tipo de lienzo.',
          textColor: '#9d174d',
          type: 'sticky',
          width: 150,
          x: 100,
          y: 280,
        },
        {
          color: '#fed7aa',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Exportación fiel:\nDescarga en PNG, SVG y PDF sin artefactos visuales.',
          textColor: '#c2410c',
          type: 'sticky',
          width: 150,
          x: 280,
          y: 280,
        },
      ];

    case 'tmpl-board-retro':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🚀 Retrospectiva Ágil de Equipo',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        // Column 1: Qué salió bien
        {
          fillColor: '#f0fdf4',
          height: 480,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#10b981',
          strokeWidth: 2,
          type: 'shape',
          width: 250,
          x: 100,
          y: 100,
        },
        {
          color: '#15803d',
          fontSize: 16,
          height: 30,
          id: uid('txt'),
          text: '🎉 ¿Qué salió bien?',
          type: 'text',
          width: 220,
          x: 120,
          y: 120,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Entregas completadas a tiempo con alta calidad.',
          textColor: '#14532d',
          type: 'sticky',
          width: 210,
          x: 120,
          y: 170,
        },
        // Column 2: Qué podemos mejorar
        {
          fillColor: '#fefce8',
          height: 480,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          type: 'shape',
          width: 250,
          x: 380,
          y: 100,
        },
        {
          color: '#b45309',
          fontSize: 16,
          height: 30,
          id: uid('txt'),
          text: '🤔 ¿Qué podemos mejorar?',
          type: 'text',
          width: 220,
          x: 400,
          y: 120,
        },
        {
          color: '#fef08a',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Reducir tiempos de revisión en pull requests.',
          textColor: '#713f12',
          type: 'sticky',
          width: 210,
          x: 400,
          y: 170,
        },
        // Column 3: Acciones a tomar
        {
          fillColor: '#eff6ff',
          height: 480,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#6366f1',
          strokeWidth: 2,
          type: 'shape',
          width: 250,
          x: 660,
          y: 100,
        },
        {
          color: '#4338ca',
          fontSize: 16,
          height: 30,
          id: uid('txt'),
          text: '⚡ Acciones concretas',
          type: 'text',
          width: 220,
          x: 680,
          y: 120,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Asignar parejas de code review diarias.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 210,
          x: 680,
          y: 170,
        },
      ];

    case 'tmpl-board-kanban':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '📋 Tablero Kanban de Tareas',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        // To Do
        {
          fillColor: '#f8fafc',
          height: 460,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#cbd5e1',
          strokeWidth: 1.5,
          type: 'shape',
          width: 220,
          x: 100,
          y: 100,
        },
        {
          color: '#334155',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '📌 Por Hacer (To Do)',
          type: 'text',
          width: 190,
          x: 115,
          y: 115,
        },
        {
          color: '#fef08a',
          fontSize: 13,
          height: 90,
          id: uid('stk'),
          text: 'Investigar nuevas librerías de renderizado.',
          textColor: '#713f12',
          type: 'sticky',
          width: 190,
          x: 115,
          y: 155,
        },
        // In Progress
        {
          fillColor: '#eff6ff',
          height: 460,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#93c5fd',
          strokeWidth: 1.5,
          type: 'shape',
          width: 220,
          x: 340,
          y: 100,
        },
        {
          color: '#1d4ed8',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '⏳ En Progreso (Doing)',
          type: 'text',
          width: 190,
          x: 355,
          y: 115,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 90,
          id: uid('stk'),
          text: 'Refactorizar componentes con fondo blanco.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 190,
          x: 355,
          y: 155,
        },
        // Done
        {
          fillColor: '#f0fdf4',
          height: 460,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#86efac',
          strokeWidth: 1.5,
          type: 'shape',
          width: 220,
          x: 580,
          y: 100,
        },
        {
          color: '#15803d',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '✅ Completado (Done)',
          type: 'text',
          width: 190,
          x: 595,
          y: 115,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 90,
          id: uid('stk'),
          text: 'Purga de base de datos y migración inicial.',
          textColor: '#14532d',
          type: 'sticky',
          width: 190,
          x: 595,
          y: 155,
        },
      ];

    case 'tmpl-board-empathy':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '👤 Mapa de Empatía del Usuario',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#f8fafc',
          height: 200,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#38bdf8',
          strokeWidth: 1.5,
          type: 'shape',
          width: 300,
          x: 100,
          y: 100,
        },
        {
          color: '#0284c7',
          fontSize: 14,
          height: 25,
          id: uid('txt'),
          text: '💭 ¿Qué piensa y siente?',
          type: 'text',
          width: 260,
          x: 120,
          y: 115,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Quiere crear diagramas sin distracciones visuales.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 260,
          x: 120,
          y: 160,
        },
        {
          fillColor: '#f8fafc',
          height: 200,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#a855f7',
          strokeWidth: 1.5,
          type: 'shape',
          width: 300,
          x: 430,
          y: 100,
        },
        {
          color: '#7e22ce',
          fontSize: 14,
          height: 25,
          id: uid('txt'),
          text: '👁️ ¿Qué ve?',
          type: 'text',
          width: 260,
          x: 450,
          y: 115,
        },
        {
          color: '#f3e8ff',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Lienzo blanco con puntos tenues y limpios.',
          textColor: '#581c87',
          type: 'sticky',
          width: 260,
          x: 450,
          y: 160,
        },
      ];

    case 'tmpl-board-journey':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🗺️ Customer Journey Map',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        {
          color: '#fef08a',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 1: Descubrimiento\nLlega mediante recomendación o búsqueda.',
          textColor: '#713f12',
          type: 'sticky',
          width: 160,
          x: 100,
          y: 110,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 2: Exploración\nElige una plantilla de pizarrón o documento.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 160,
          x: 290,
          y: 110,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 3: Creación\nTrabaja en un lienzo blanco sin distracciones.',
          textColor: '#14532d',
          type: 'sticky',
          width: 160,
          x: 480,
          y: 110,
        },
        {
          color: '#fed7aa',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 4: Exportación\nDescarga su trabajo listo para compartir.',
          textColor: '#c2410c',
          type: 'sticky',
          width: 160,
          x: 670,
          y: 110,
        },
      ];

    case 'tmpl-board-business':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '📊 Canvas de Modelo de Negocio',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#eff6ff',
          height: 280,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          type: 'shape',
          width: 220,
          x: 350,
          y: 100,
        },
        {
          color: '#1d4ed8',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '💎 Propuesta de Valor',
          type: 'text',
          width: 190,
          x: 365,
          y: 115,
        },
        {
          color: '#dbeafe',
          fontSize: 13,
          height: 140,
          id: uid('stk'),
          text: 'Herramientas visuales integradas con zona de trabajo blanca y colaboración en tiempo real.',
          textColor: '#1e3a8a',
          type: 'sticky',
          width: 190,
          x: 365,
          y: 160,
        },
      ];

    case 'tmpl-board-matrix':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '⚖️ Matriz de Priorización (Impacto vs Esfuerzo)',
          type: 'text',
          width: 550,
          x: 100,
          y: 40,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 120,
          id: uid('stk'),
          text: '🚀 Quick Win (Alto I / Bajo E):\nEstandarizar fondos blancos en todos los lienzos.',
          textColor: '#14532d',
          type: 'sticky',
          width: 200,
          x: 100,
          y: 110,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 120,
          id: uid('stk'),
          text: '🎯 Estratégico (Alto I / Alto E):\nMotor colaborativo de documentos en tiempo real.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 200,
          x: 330,
          y: 110,
        },
      ];

    case 'tmpl-board-wireframe':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '📱 Bocetos de Interfaz y Wireframes',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#ffffff',
          height: 360,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#64748b',
          strokeWidth: 2,
          type: 'shape',
          width: 260,
          x: 100,
          y: 100,
        },
        {
          color: '#475569',
          fontSize: 14,
          height: 25,
          id: uid('txt'),
          text: '📱 Vista Móvil (Pantalla 1)',
          type: 'text',
          width: 220,
          x: 120,
          y: 120,
        },
      ];

    case 'tmpl-board-roadmap':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🎯 Roadmap Trimestral de Producto',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Q1: Suite de Plantillas Blancas\n10 por cada tipo de lienzo.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 170,
          x: 100,
          y: 110,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Q2: Exportación Avanzada\nSoporte vector SVG y PDF editorial.',
          textColor: '#14532d',
          type: 'sticky',
          width: 170,
          x: 300,
          y: 110,
        },
      ];

    case 'tmpl-board-swot':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🛡️ Análisis FODA / SWOT',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#f0fdf4',
          height: 220,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#86efac',
          strokeWidth: 2,
          type: 'shape',
          width: 280,
          x: 100,
          y: 100,
        },
        {
          color: '#15803d',
          fontSize: 16,
          height: 25,
          id: uid('txt'),
          text: '💪 Fortalezas',
          type: 'text',
          width: 240,
          x: 120,
          y: 115,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Diseño limpio y consistente en todos los módulos.',
          textColor: '#14532d',
          type: 'sticky',
          width: 240,
          x: 120,
          y: 160,
        },
        {
          fillColor: '#eff6ff',
          height: 220,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#93c5fd',
          strokeWidth: 2,
          type: 'shape',
          width: 280,
          x: 410,
          y: 100,
        },
        {
          color: '#1d4ed8',
          fontSize: 16,
          height: 25,
          id: uid('txt'),
          text: '🚀 Oportunidades',
          type: 'text',
          width: 240,
          x: 430,
          y: 115,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Adopción acelerada por equipos de diseño y producto.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 240,
          x: 430,
          y: 160,
        },
      ];

    default:
      return [];
  }
}
