import { convertDiagramToBoardElements } from '../views/board/board-elements.manager.js';
import { BoardElement } from '../views/board/board.types.js';
import { getCustomDiagramProject } from './diagram-templates.data.js';
import { ALL_PRESETS } from './templates.config.js';

export function getBoardTemplateElements(templateId?: string | null): BoardElement[] {
  if (!templateId) return [];

  const uid = (prefix: string) => `${prefix}_${Math.random().toString(36).substring(2, 9)}`;

  switch (templateId) {
    case 'tmpl-board-showcase':
      return [
        {
          color: '#0f172a',
          fontSize: 32,
          height: 48,
          id: 'txt_showcase_title',
          text: '🎨 Spriteboard - Showcase Integral de Elementos y Variaciones',
          type: 'text',
          width: 1050,
          x: 100,
          y: 40,
        },
        {
          color: '#64748b',
          fontSize: 15,
          height: 28,
          id: 'txt_showcase_sub',
          text: 'Pizarrón infinito con todas las 11 figuras geométricas, 8 notas adhesivas, componentes de diagramas, mapas radiales, tablas, pixel art y trazos libres.',
          type: 'text',
          width: 1150,
          x: 100,
          y: 95,
        },
        {
          fillColor: '#ecfdf5',
          fontSize: 13,
          height: 38,
          id: 'shp_badge_status',
          shapeType: 'pill',
          strokeColor: '#10b981',
          strokeWidth: 1.5,
          text: '✨ 100% Unificado & Funcional',
          textColor: '#065f46',
          type: 'shape',
          width: 240,
          x: 1260,
          y: 55,
        },
        {
          backgroundColor: '#f8fafc',
          borderColor: '#cbd5e1',
          borderWidth: 1.5,
          height: 460,
          id: 'sec_shapes',
          title: '📐 Figuras Geométricas y Bordes (11 Formas Canónicas)',
          titleColor: '#1e293b',
          type: 'section',
          width: 1400,
          x: 100,
          y: 150,
        },
        {
          fillColor: '#eff6ff',
          fontSize: 13,
          height: 85,
          id: 'shp_rect',
          shapeType: 'rect',
          strokeColor: '#3b82f6',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Rectángulo',
          textColor: '#1e40af',
          type: 'shape',
          width: 160,
          x: 130,
          y: 220,
        },
        {
          borderRadius: 14,
          fillColor: '#f0fdf4',
          fontSize: 13,
          height: 85,
          id: 'shp_round_rect',
          shapeType: 'round-rect',
          strokeColor: '#10b981',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Redondeado',
          textColor: '#065f46',
          type: 'shape',
          width: 160,
          x: 320,
          y: 220,
        },
        {
          fillColor: '#fef2f2',
          fontSize: 13,
          height: 95,
          id: 'shp_circle',
          shapeType: 'circle',
          strokeColor: '#ef4444',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Círculo',
          textColor: '#991b1b',
          type: 'shape',
          width: 95,
          x: 510,
          y: 215,
        },
        {
          fillColor: '#fffbeb',
          fontSize: 13,
          height: 95,
          id: 'shp_triangle',
          shapeType: 'triangle',
          strokeColor: '#f59e0b',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Triángulo',
          textColor: '#92400e',
          type: 'shape',
          width: 130,
          x: 635,
          y: 215,
        },
        {
          fillColor: '#faf5ff',
          fontSize: 13,
          height: 105,
          id: 'shp_diamond',
          shapeType: 'diamond',
          strokeColor: '#a855f7',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Rombo',
          textColor: '#6b21a8',
          type: 'shape',
          width: 110,
          x: 795,
          y: 210,
        },
        {
          fillColor: '#ecfeff',
          fontSize: 13,
          height: 85,
          id: 'shp_parallel',
          shapeType: 'parallelogram',
          strokeColor: '#06b6d4',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Paralelogramo',
          textColor: '#155e75',
          type: 'shape',
          width: 150,
          x: 935,
          y: 220,
        },
        {
          fillColor: '#fdf4ff',
          fontSize: 13,
          height: 85,
          id: 'shp_cylinder',
          shapeType: 'cylinder',
          strokeColor: '#d946ef',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Cilindro / DB',
          textColor: '#86198f',
          type: 'shape',
          width: 130,
          x: 1115,
          y: 220,
        },
        {
          fillColor: '#f0fdfa',
          fontSize: 13,
          height: 55,
          id: 'shp_pill',
          shapeType: 'pill',
          strokeColor: '#14b8a6',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Píldora',
          textColor: '#115e59',
          type: 'shape',
          width: 140,
          x: 1275,
          y: 235,
        },
        {
          fillColor: '#f8fafc',
          fontSize: 13,
          height: 85,
          id: 'shp_document',
          shapeType: 'document',
          strokeColor: '#64748b',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Documento',
          textColor: '#334155',
          type: 'shape',
          width: 135,
          x: 130,
          y: 340,
        },
        {
          fillColor: '#f0f9ff',
          fontSize: 13,
          height: 90,
          id: 'shp_cloud',
          shapeType: 'cloud',
          strokeColor: '#0284c7',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Nube / Cloud',
          textColor: '#075985',
          type: 'shape',
          width: 155,
          x: 295,
          y: 335,
        },
        {
          fillColor: '#fefce8',
          fontSize: 13,
          height: 100,
          id: 'shp_star',
          shapeType: 'star',
          strokeColor: '#eab308',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Estrella',
          textColor: '#854d0e',
          type: 'shape',
          width: 100,
          x: 480,
          y: 330,
        },
        {
          fillColor: '#f5f3ff',
          fontSize: 13,
          height: 80,
          id: 'shp_dotted',
          shapeType: 'rect',
          strokeColor: '#7c3aed',
          strokeStyle: 'dotted',
          strokeWidth: 3,
          text: 'Borde Punteado',
          textColor: '#5b21b6',
          type: 'shape',
          width: 170,
          x: 610,
          y: 340,
        },
        {
          borderRadius: 12,
          fillColor: '#fff7ed',
          fontSize: 13,
          height: 80,
          id: 'shp_dashed',
          shapeType: 'round-rect',
          strokeColor: '#ea580c',
          strokeStyle: 'dashed',
          strokeWidth: 3,
          text: 'Borde Discontinuo',
          textColor: '#9a3412',
          type: 'shape',
          width: 170,
          x: 810,
          y: 340,
        },
        {
          borderRadius: 12,
          fillColor: '#ecfdf5',
          fontSize: 13,
          height: 80,
          id: 'shp_opacity',
          opacity: 0.6,
          shapeType: 'round-rect',
          strokeColor: '#059669',
          strokeStyle: 'solid',
          strokeWidth: 2,
          text: 'Opacidad 60%',
          textColor: '#065f46',
          type: 'shape',
          width: 160,
          x: 1010,
          y: 340,
        },
        {
          fillColor: '#fef3c7',
          fontSize: 13,
          height: 95,
          id: 'shp_thick',
          shapeType: 'circle',
          strokeColor: '#d97706',
          strokeStyle: 'solid',
          strokeWidth: 4,
          text: 'Borde 4px',
          textColor: '#78350f',
          type: 'shape',
          width: 95,
          x: 1200,
          y: 330,
        },
        {
          backgroundColor: '#fffbeb',
          borderColor: '#fde68a',
          borderWidth: 1.5,
          height: 460,
          id: 'sec_stickies',
          title: '📝 Notas Adhesivas (8 Colores Canónicos SSOT)',
          titleColor: '#78350f',
          type: 'section',
          width: 1400,
          x: 1550,
          y: 150,
        },
        {
          color: '#fef08a',
          fontSize: 13,
          height: 140,
          id: 'stk_yellow',
          text: '📌 Idea Principal\nAmarillo clásico para notas rápidas, ideas clave y recordatorios generales.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 1580,
          y: 220,
        },
        {
          color: '#fed7aa',
          fontSize: 13,
          height: 140,
          id: 'stk_orange',
          text: '🔥 Prioridad Alta\nNaranja para temas urgentes, llamadas de atención o sprints críticos.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 1790,
          y: 220,
        },
        {
          color: '#fbcfe8',
          fontSize: 13,
          height: 140,
          id: 'stk_pink',
          text: '💡 Innovación & Diseño\nRosa para propuestas creativas, brainstorming visual e interfaces.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 2000,
          y: 220,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 140,
          id: 'stk_blue',
          text: '🚀 Arquitectura & Tech\nAzul para requerimientos de backend, base de datos y APIs.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 2210,
          y: 220,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 140,
          id: 'stk_green',
          text: '✅ Tarea Completada\nVerde para hitos alcanzados, features validadas y entregables.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 1580,
          y: 390,
        },
        {
          color: '#e9d5ff',
          fontSize: 13,
          height: 140,
          id: 'stk_purple',
          text: '🔮 Experimentación\nMorado para research, pruebas de concepto y benchmarking.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 1790,
          y: 390,
        },
        {
          color: '#fecaca',
          fontSize: 13,
          height: 140,
          id: 'stk_red',
          text: '⚠️ Riesgos y Bloqueos\nRojo para incidencias, dependencias bloqueantes y alertas.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 2000,
          y: 390,
        },
        {
          color: '#f1f5f9',
          fontSize: 13,
          height: 140,
          id: 'stk_gray',
          text: '📋 Contexto & Enlaces\nGris para notas de referencia, documentación técnica y metadatos.',
          textColor: '#1e293b',
          type: 'sticky',
          width: 185,
          x: 2210,
          y: 390,
        },
        {
          backgroundColor: '#f0fdf4',
          borderColor: '#bbf7d0',
          borderWidth: 1.5,
          height: 520,
          id: 'sec_flow',
          title: '🔄 Diagrama de Flujo y Conectores (Ortogonales, Curvos y Rectos)',
          titleColor: '#14532d',
          type: 'section',
          width: 1400,
          x: 100,
          y: 650,
        },
        {
          fillColor: '#ecfdf5',
          fontSize: 13,
          height: 55,
          id: 'flow_start',
          shapeType: 'pill',
          strokeColor: '#10b981',
          strokeWidth: 2,
          text: 'Inicio de Sesión',
          textColor: '#065f46',
          type: 'shape',
          width: 150,
          x: 140,
          y: 780,
        },
        {
          fillColor: '#f5f3ff',
          fontSize: 13,
          height: 65,
          id: 'flow_input',
          shapeType: 'parallelogram',
          strokeColor: '#8b5cf6',
          strokeWidth: 2,
          text: 'Datos de Usuario',
          textColor: '#5b21b6',
          type: 'shape',
          width: 165,
          x: 350,
          y: 775,
        },
        {
          fillColor: '#fffbeb',
          fontSize: 13,
          height: 115,
          id: 'flow_eval',
          shapeType: 'diamond',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          text: '¿Credenciales Válidas?',
          textColor: '#92400e',
          type: 'shape',
          width: 140,
          x: 580,
          y: 750,
        },
        {
          fillColor: '#ecfeff',
          fontSize: 13,
          height: 80,
          id: 'flow_db',
          shapeType: 'cylinder',
          strokeColor: '#06b6d4',
          strokeWidth: 2,
          text: 'Consultar DB',
          textColor: '#155e75',
          type: 'shape',
          width: 140,
          x: 580,
          y: 950,
        },
        {
          fillColor: '#dcfce7',
          fontSize: 13,
          height: 55,
          id: 'flow_success',
          shapeType: 'pill',
          strokeColor: '#16a34a',
          strokeWidth: 2,
          text: 'Acceso Permitido',
          textColor: '#166534',
          type: 'shape',
          width: 160,
          x: 820,
          y: 780,
        },
        {
          fillColor: '#f0f9ff',
          fontSize: 13,
          height: 85,
          id: 'flow_cloud',
          shapeType: 'cloud',
          strokeColor: '#0284c7',
          strokeWidth: 2,
          text: 'Sincronizar Cloud',
          textColor: '#075985',
          type: 'shape',
          width: 160,
          x: 1060,
          y: 765,
        },
        {
          fillColor: '#fef2f2',
          fontSize: 13,
          height: 80,
          id: 'flow_error',
          shapeType: 'document',
          strokeColor: '#ef4444',
          strokeWidth: 2,
          text: 'Registro de Alerta',
          textColor: '#991b1b',
          type: 'shape',
          width: 150,
          x: 820,
          y: 950,
        },
        {
          fillColor: '#f8fafc',
          fontSize: 13,
          height: 55,
          id: 'flow_end',
          shapeType: 'pill',
          strokeColor: '#475569',
          strokeWidth: 2,
          text: 'Fin del Proceso',
          textColor: '#1e293b',
          type: 'shape',
          width: 140,
          x: 1290,
          y: 780,
        },
        {
          arrowEnd: true,
          color: '#10b981',
          fontSize: 12,
          fromId: 'flow_start',
          id: 'conn_f1',
          label: 'Enviar',
          strokeStyle: 'solid',
          strokeWidth: 2,
          style: 'straight',
          toId: 'flow_input',
          type: 'connector',
        },
        {
          arrowEnd: true,
          color: '#8b5cf6',
          fontSize: 12,
          fromId: 'flow_input',
          id: 'conn_f2',
          label: 'Procesar',
          strokeStyle: 'solid',
          strokeWidth: 2,
          style: 'straight',
          toId: 'flow_eval',
          type: 'connector',
        },
        {
          arrowEnd: true,
          color: '#06b6d4',
          fontSize: 12,
          fromId: 'flow_eval',
          id: 'conn_f3',
          label: 'Validar',
          strokeStyle: 'solid',
          strokeWidth: 2,
          style: 'straight',
          toId: 'flow_db',
          type: 'connector',
        },
        {
          arrowEnd: true,
          color: '#16a34a',
          fontSize: 12,
          fromId: 'flow_eval',
          id: 'conn_f4',
          label: 'Sí (Válido)',
          strokeStyle: 'solid',
          strokeWidth: 2,
          style: 'straight',
          toId: 'flow_success',
          type: 'connector',
        },
        {
          arrowEnd: true,
          color: '#0284c7',
          fontSize: 12,
          fromId: 'flow_success',
          id: 'conn_f5',
          label: 'Broadcast',
          strokeStyle: 'solid',
          strokeWidth: 2,
          style: 'curved',
          toId: 'flow_cloud',
          type: 'connector',
        },
        {
          arrowEnd: true,
          color: '#475569',
          fontSize: 12,
          fromId: 'flow_cloud',
          id: 'conn_f6',
          label: 'Completar',
          strokeStyle: 'solid',
          strokeWidth: 2,
          style: 'straight',
          toId: 'flow_end',
          type: 'connector',
        },
        {
          arrowEnd: true,
          color: '#ef4444',
          fontSize: 12,
          fromId: 'flow_eval',
          id: 'conn_f7',
          label: 'No (Inválido)',
          strokeStyle: 'solid',
          strokeWidth: 2,
          style: 'orthogonal',
          toId: 'flow_error',
          type: 'connector',
        },
        {
          backgroundColor: '#faf5ff',
          borderColor: '#e9d5ff',
          borderWidth: 1.5,
          height: 520,
          id: 'sec_mindmap',
          title: '🧠 Mapa Mental con Nodos Radiales y Conectores Curvos',
          titleColor: '#581c87',
          type: 'section',
          width: 1400,
          x: 1550,
          y: 650,
        },
        {
          borderRadius: 16,
          fillColor: '#e0e7ff',
          fontSize: 15,
          height: 70,
          id: 'mm_root',
          isMindMapNode: true,
          shapeType: 'round-rect',
          strokeColor: '#6366f1',
          strokeWidth: 3,
          text: 'Spriteboard Ecosistema',
          textColor: '#3730a3',
          type: 'shape',
          width: 210,
          x: 2145,
          y: 875,
        },
        {
          fillColor: '#dbeafe',
          fontSize: 13,
          height: 50,
          id: 'mm_b1',
          isMindMapNode: true,
          shapeType: 'pill',
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          text: 'Pizarrón Infinito',
          textColor: '#1e40af',
          type: 'shape',
          width: 180,
          x: 1700,
          y: 720,
        },
        {
          arrowEnd: true,
          color: '#3b82f6',
          fromId: 'mm_root',
          id: 'conn_mm_b1',
          strokeWidth: 2.5,
          style: 'curved',
          toId: 'mm_b1',
          type: 'connector',
        },
        {
          fillColor: '#d1fae5',
          fontSize: 13,
          height: 50,
          id: 'mm_b2',
          isMindMapNode: true,
          shapeType: 'pill',
          strokeColor: '#10b981',
          strokeWidth: 2,
          text: 'Documentos Doc',
          textColor: '#065f46',
          type: 'shape',
          width: 180,
          x: 2590,
          y: 720,
        },
        {
          arrowEnd: true,
          color: '#10b981',
          fromId: 'mm_root',
          id: 'conn_mm_b2',
          strokeWidth: 2.5,
          style: 'curved',
          toId: 'mm_b2',
          type: 'connector',
        },
        {
          fillColor: '#ffedd5',
          fontSize: 13,
          height: 50,
          id: 'mm_b3',
          isMindMapNode: true,
          shapeType: 'pill',
          strokeColor: '#f97316',
          strokeWidth: 2,
          text: 'Colaboración Real-time',
          textColor: '#9a3412',
          type: 'shape',
          width: 190,
          x: 1660,
          y: 885,
        },
        {
          arrowEnd: true,
          color: '#f97316',
          fromId: 'mm_root',
          id: 'conn_mm_b3',
          strokeWidth: 2.5,
          style: 'curved',
          toId: 'mm_b3',
          type: 'connector',
        },
        {
          fillColor: '#f3e8ff',
          fontSize: 13,
          height: 50,
          id: 'mm_b4',
          isMindMapNode: true,
          shapeType: 'pill',
          strokeColor: '#a855f7',
          strokeWidth: 2,
          text: 'Pixel Art Integrado',
          textColor: '#6b21a8',
          type: 'shape',
          width: 185,
          x: 2620,
          y: 885,
        },
        {
          arrowEnd: true,
          color: '#a855f7',
          fromId: 'mm_root',
          id: 'conn_mm_b4',
          strokeWidth: 2.5,
          style: 'curved',
          toId: 'mm_b4',
          type: 'connector',
        },
        {
          fillColor: '#ffe4e6',
          fontSize: 13,
          height: 50,
          id: 'mm_b5',
          isMindMapNode: true,
          shapeType: 'pill',
          strokeColor: '#f43f5e',
          strokeWidth: 2,
          text: 'Seguridad & Roles',
          textColor: '#9f1239',
          type: 'shape',
          width: 180,
          x: 1720,
          y: 1050,
        },
        {
          arrowEnd: true,
          color: '#f43f5e',
          fromId: 'mm_root',
          id: 'conn_mm_b5',
          strokeWidth: 2.5,
          style: 'curved',
          toId: 'mm_b5',
          type: 'connector',
        },
        {
          fillColor: '#fef3c7',
          fontSize: 13,
          height: 50,
          id: 'mm_b6',
          isMindMapNode: true,
          shapeType: 'pill',
          strokeColor: '#d97706',
          strokeWidth: 2,
          text: 'Plantillas & Modelos',
          textColor: '#92400e',
          type: 'shape',
          width: 180,
          x: 2560,
          y: 1050,
        },
        {
          arrowEnd: true,
          color: '#d97706',
          fromId: 'mm_root',
          id: 'conn_mm_b6',
          strokeWidth: 2.5,
          style: 'curved',
          toId: 'mm_b6',
          type: 'connector',
        },
        {
          backgroundColor: '#f1f5f9',
          borderColor: '#e2e8f0',
          borderWidth: 1.5,
          height: 480,
          id: 'sec_pixel',
          title: '👾 Pixel Art & Grilla Editable',
          titleColor: '#334155',
          type: 'section',
          width: 680,
          x: 100,
          y: 1210,
        },
        {
          backgroundColor: '#1e293b',
          data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAZElEQVR4nGOQ07T+TwlmQOZ8nccNxrgUY5OHGwCSeO/iAsbYDMElz4AuiU0RPnmcBsAU4ZMjaAA+jGIAqYZghAEphuCMBWIMwRY7GAYQEysEDSAmXRA0gJiUSdAAOVLzwtA0AAAccd+Y169fGgAAAABJRU5ErkJggg==',
          gridHeight: 16,
          gridWidth: 16,
          height: 256,
          id: 'px_heart_grid',
          pixelSize: 16,
          showGrid: true,
          type: 'pixel-grid',
          width: 256,
          x: 140,
          y: 1300,
        },
        {
          color: '#1e293b',
          fontSize: 16,
          height: 26,
          id: 'txt_pixel_header',
          text: '🎨 Grilla de Píxeles 16×16',
          type: 'text',
          width: 300,
          x: 425,
          y: 1300,
        },
        {
          color: '#64748b',
          fontSize: 13,
          height: 110,
          id: 'txt_pixel_desc',
          text: 'Grilla totalmente interactiva dentro del pizarrón infinito.\n\nHerramientas disponibles:\n• Lápiz (P)\n• Borrador (E)\n• Bote de pintura (G)\n• Selector de color (I)\n• Paleta PICO-8 / Game Boy',
          type: 'text',
          width: 320,
          x: 425,
          y: 1340,
        },
        {
          fillColor: '#fee2e2',
          fontSize: 12,
          height: 36,
          id: 'shp_pixel_badge',
          shapeType: 'pill',
          strokeColor: '#ef4444',
          strokeWidth: 1.5,
          text: '❤️ Sprite Corazón Dorado',
          textColor: '#991b1b',
          type: 'shape',
          width: 200,
          x: 425,
          y: 1500,
        },
        {
          backgroundColor: '#f8fafc',
          borderColor: '#cbd5e1',
          borderWidth: 1.5,
          height: 480,
          id: 'sec_table',
          title: '📊 Tablas y Matrices Estructuradas',
          titleColor: '#1e293b',
          type: 'section',
          width: 680,
          x: 820,
          y: 1210,
        },
        {
          borderColor: '#cbd5e1',
          borderWidth: 1.5,
          colWidths: [180, 140, 270],
          cols: 3,
          data: [[{"text": "Módulo / Herramienta", "textColor": "#ffffff", "backgroundColor": "#2563eb"}, {"text": "Estado", "textColor": "#ffffff", "backgroundColor": "#2563eb"}, {"text": "Capacidades Clave", "textColor": "#ffffff", "backgroundColor": "#2563eb"}], [{"text": "Pizarrón Infinito", "textColor": "#1e293b", "backgroundColor": "#ffffff"}, {"text": "✅ 100% Listo", "textColor": "#166534", "backgroundColor": "#f0fdf4"}, {"text": "Figuras, notas, diagramas y tablas", "textColor": "#475569", "backgroundColor": "#ffffff"}], [{"text": "Documentos Doc", "textColor": "#1e293b", "backgroundColor": "#ffffff"}, {"text": "✅ 100% Listo", "textColor": "#166534", "backgroundColor": "#f0fdf4"}, {"text": "Paginado, formato rico y Word/PDF", "textColor": "#475569", "backgroundColor": "#ffffff"}], [{"text": "Pixel Art Embebido", "textColor": "#1e293b", "backgroundColor": "#ffffff"}, {"text": "✅ 100% Listo", "textColor": "#166534", "backgroundColor": "#f0fdf4"}, {"text": "Edición pixelada en el pizarrón", "textColor": "#475569", "backgroundColor": "#ffffff"}], [{"text": "Plantillas SSOT", "textColor": "#1e293b", "backgroundColor": "#ffffff"}, {"text": "✅ 100% Listo", "textColor": "#166534", "backgroundColor": "#f0fdf4"}, {"text": "Categorías Board y Doc unificadas", "textColor": "#475569", "backgroundColor": "#ffffff"}]],
          fontSize: 13,
          height: 260,
          id: 'tbl_modules',
          rowHeights: [45, 48, 48, 48, 48],
          rows: 5,
          type: 'table',
          width: 600,
          x: 860,
          y: 1300,
        },
        {
          backgroundColor: '#fdf4ff',
          borderColor: '#f5d0fe',
          borderWidth: 1.5,
          height: 480,
          id: 'sec_strokes',
          title: '✍️ Herramientas de Trazo y Dibujo Libre',
          titleColor: '#701a75',
          type: 'section',
          width: 1400,
          x: 1550,
          y: 1210,
        },
        {
          color: '#3b82f6',
          id: 'strk_pen',
          opacity: 1.0,
          points: [{"x": 1600, "y": 1357.5}, {"x": 1614, "y": 1321.6025641025642}, {"x": 1628, "y": 1359.2948717948718}, {"x": 1642, "y": 1319.8076923076924}, {"x": 1656, "y": 1361.0897435897436}, {"x": 1670, "y": 1318.0128205128206}, {"x": 1684, "y": 1362.8846153846155}, {"x": 1698, "y": 1316.2179487179487}, {"x": 1712, "y": 1364.679487179487}, {"x": 1726, "y": 1314.423076923077}, {"x": 1740, "y": 1366.474358974359}, {"x": 1754, "y": 1312.628205128205}, {"x": 1768, "y": 1368.2692307692307}, {"x": 1782, "y": 1310.8333333333333}, {"x": 1796, "y": 1370.0641025641025}, {"x": 1810, "y": 1309.0384615384614}, {"x": 1824, "y": 1371.8589743589744}, {"x": 1838, "y": 1307.2435897435898}, {"x": 1852, "y": 1373.6538461538462}, {"x": 1866, "y": 1305.448717948718}, {"x": 1880, "y": 1374.551282051282}, {"x": 1894, "y": 1306.3461538461538}, {"x": 1908, "y": 1372.7564102564102}, {"x": 1922, "y": 1308.1410256410256}, {"x": 1936, "y": 1370.9615384615386}, {"x": 1950, "y": 1309.9358974358975}, {"x": 1964, "y": 1369.1666666666667}, {"x": 1978, "y": 1311.7307692307693}, {"x": 1992, "y": 1367.371794871795}, {"x": 2006, "y": 1313.525641025641}, {"x": 2020, "y": 1365.576923076923}, {"x": 2034, "y": 1315.3205128205127}, {"x": 2048, "y": 1363.7820512820513}, {"x": 2062, "y": 1317.1153846153845}, {"x": 2076, "y": 1361.9871794871794}, {"x": 2090, "y": 1318.9102564102564}, {"x": 2104, "y": 1360.1923076923076}, {"x": 2118, "y": 1320.7051282051282}, {"x": 2132, "y": 1358.3974358974358}, {"x": 2146, "y": 1322.5}],
          size: 3.5,
          strokeStyle: 'solid',
          tool: 'pen',
          type: 'stroke',
        },
        {
          color: '#1e40af',
          fontSize: 13,
          height: 24,
          id: 'txt_strk_pen',
          text: '🖊️ Pluma de Trazo Fino (Pen)',
          type: 'text',
          width: 250,
          x: 1600,
          y: 1390,
        },
        {
          color: '#10b981',
          id: 'strk_marker',
          opacity: 1.0,
          points: [{"x": 2200, "y": 1365}, {"x": 2215, "y": 1365}, {"x": 2230, "y": 1365}, {"x": 2245, "y": 1315}, {"x": 2260, "y": 1315}, {"x": 2275, "y": 1315}, {"x": 2290, "y": 1365}, {"x": 2305, "y": 1365}, {"x": 2320, "y": 1365}, {"x": 2335, "y": 1315}, {"x": 2350, "y": 1315}, {"x": 2365, "y": 1315}, {"x": 2380, "y": 1365}, {"x": 2395, "y": 1365}, {"x": 2410, "y": 1365}, {"x": 2425, "y": 1315}, {"x": 2440, "y": 1315}, {"x": 2455, "y": 1315}, {"x": 2470, "y": 1365}, {"x": 2485, "y": 1365}, {"x": 2500, "y": 1365}, {"x": 2515, "y": 1315}, {"x": 2530, "y": 1315}, {"x": 2545, "y": 1315}, {"x": 2560, "y": 1365}, {"x": 2575, "y": 1365}, {"x": 2590, "y": 1365}, {"x": 2605, "y": 1315}, {"x": 2620, "y": 1315}, {"x": 2635, "y": 1315}, {"x": 2650, "y": 1365}, {"x": 2665, "y": 1365}, {"x": 2680, "y": 1365}, {"x": 2695, "y": 1315}, {"x": 2710, "y": 1315}],
          size: 8,
          strokeStyle: 'solid',
          tool: 'marker',
          type: 'stroke',
        },
        {
          color: '#065f46',
          fontSize: 13,
          height: 24,
          id: 'txt_strk_marker',
          text: '🖍️ Marcador Firme (Marker)',
          type: 'text',
          width: 250,
          x: 2200,
          y: 1390,
        },
        {
          color: '#facc15',
          id: 'strk_highlighter',
          opacity: 0.5,
          points: [{"x": 1600, "y": 1510}, {"x": 1850, "y": 1510}, {"x": 2050, "y": 1510}],
          size: 28,
          strokeStyle: 'solid',
          tool: 'highlighter',
          type: 'stroke',
        },
        {
          color: '#854d0e',
          fontSize: 15,
          height: 26,
          id: 'txt_strk_highlighter',
          text: '✨ Texto Resaltado con Resaltador Semi-Transparente',
          type: 'text',
          width: 450,
          x: 1610,
          y: 1498,
        },
        {
          color: '#ef4444',
          id: 'strk_dashed',
          opacity: 1.0,
          points: [{"x": 2200, "y": 1510}, {"x": 2218, "y": 1510}, {"x": 2236, "y": 1510}, {"x": 2254, "y": 1510}, {"x": 2272, "y": 1510}, {"x": 2290, "y": 1510}, {"x": 2308, "y": 1510}, {"x": 2326, "y": 1510}, {"x": 2344, "y": 1510}, {"x": 2362, "y": 1510}, {"x": 2380, "y": 1510}, {"x": 2398, "y": 1510}, {"x": 2416, "y": 1510}, {"x": 2434, "y": 1510}, {"x": 2452, "y": 1510}, {"x": 2470, "y": 1510}],
          size: 4,
          strokeStyle: 'dashed',
          tool: 'pen',
          type: 'stroke',
        },
        {
          color: '#991b1b',
          fontSize: 13,
          height: 24,
          id: 'txt_strk_dashed',
          text: 'Trazo Dashed Rojo',
          type: 'text',
          width: 200,
          x: 2200,
          y: 1540,
        },
        {
          color: '#8b5cf6',
          id: 'strk_dotted',
          opacity: 1.0,
          points: [{"x": 2550, "y": 1510}, {"x": 2568, "y": 1510}, {"x": 2586, "y": 1510}, {"x": 2604, "y": 1510}, {"x": 2622, "y": 1510}, {"x": 2640, "y": 1510}, {"x": 2658, "y": 1510}, {"x": 2676, "y": 1510}, {"x": 2694, "y": 1510}, {"x": 2712, "y": 1510}, {"x": 2730, "y": 1510}, {"x": 2748, "y": 1510}, {"x": 2766, "y": 1510}, {"x": 2784, "y": 1510}, {"x": 2802, "y": 1510}, {"x": 2820, "y": 1510}],
          size: 4,
          strokeStyle: 'dotted',
          tool: 'pen',
          type: 'stroke',
        },
        {
          color: '#5b21b6',
          fontSize: 13,
          height: 24,
          id: 'txt_strk_dotted',
          text: 'Trazo Dotted Morado',
          type: 'text',
          width: 200,
          x: 2550,
          y: 1540,
        },
      ];

    case 'tmpl-board-brainstorm':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '💡 Lluvia de Ideas y Notas Rápidas',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        {
          color: '#fef08a',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Nueva funcionalidad:\nLienzo visual blanco para máxima concentración.',
          textColor: '#713f12',
          type: 'sticky',
          width: 150,
          x: 100,
          y: 110,
        },
        {
          color: '#bae6fd',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Optimización de UX:\nAtajos de teclado intuitivos y herramientas rápidas.',
          textColor: '#0369a1',
          type: 'sticky',
          width: 150,
          x: 280,
          y: 110,
        },
        {
          color: '#bbf7d0',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Colaboración en vivo:\nCursores de equipo con colores diferenciados.',
          textColor: '#15803d',
          type: 'sticky',
          width: 150,
          x: 460,
          y: 110,
        },
        {
          color: '#fbcfe8',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Plantillas prediseñadas:\n10 plantillas limpias por cada tipo de lienzo.',
          textColor: '#9d174d',
          type: 'sticky',
          width: 150,
          x: 100,
          y: 280,
        },
        {
          color: '#fed7aa',
          fontSize: 14,
          height: 140,
          id: uid('stk'),
          text: 'Exportación fiel:\nDescarga en PNG, SVG y PDF sin artefactos visuales.',
          textColor: '#c2410c',
          type: 'sticky',
          width: 150,
          x: 280,
          y: 280,
        },
      ];

    case 'tmpl-board-retro':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🚀 Retrospectiva Ágil de Equipo',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        // Column 1: Qué salió bien
        {
          fillColor: '#f0fdf4',
          height: 480,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#10b981',
          strokeWidth: 2,
          type: 'shape',
          width: 250,
          x: 100,
          y: 100,
        },
        {
          color: '#15803d',
          fontSize: 16,
          height: 30,
          id: uid('txt'),
          text: '🎉 ¿Qué salió bien?',
          type: 'text',
          width: 220,
          x: 120,
          y: 120,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Entregas completadas a tiempo con alta calidad.',
          textColor: '#14532d',
          type: 'sticky',
          width: 210,
          x: 120,
          y: 170,
        },
        // Column 2: Qué podemos mejorar
        {
          fillColor: '#fefce8',
          height: 480,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          type: 'shape',
          width: 250,
          x: 380,
          y: 100,
        },
        {
          color: '#b45309',
          fontSize: 16,
          height: 30,
          id: uid('txt'),
          text: '🤔 ¿Qué podemos mejorar?',
          type: 'text',
          width: 220,
          x: 400,
          y: 120,
        },
        {
          color: '#fef08a',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Reducir tiempos de revisión en pull requests.',
          textColor: '#713f12',
          type: 'sticky',
          width: 210,
          x: 400,
          y: 170,
        },
        // Column 3: Acciones a tomar
        {
          fillColor: '#eff6ff',
          height: 480,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#6366f1',
          strokeWidth: 2,
          type: 'shape',
          width: 250,
          x: 660,
          y: 100,
        },
        {
          color: '#4338ca',
          fontSize: 16,
          height: 30,
          id: uid('txt'),
          text: '⚡ Acciones concretas',
          type: 'text',
          width: 220,
          x: 680,
          y: 120,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Asignar parejas de code review diarias.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 210,
          x: 680,
          y: 170,
        },
      ];

    case 'tmpl-board-kanban':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '📋 Tablero Kanban de Tareas',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        // To Do
        {
          fillColor: '#f8fafc',
          height: 460,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#cbd5e1',
          strokeWidth: 1.5,
          type: 'shape',
          width: 220,
          x: 100,
          y: 100,
        },
        {
          color: '#334155',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '📌 Por Hacer (To Do)',
          type: 'text',
          width: 190,
          x: 115,
          y: 115,
        },
        {
          color: '#fef08a',
          fontSize: 13,
          height: 90,
          id: uid('stk'),
          text: 'Investigar nuevas librerías de renderizado.',
          textColor: '#713f12',
          type: 'sticky',
          width: 190,
          x: 115,
          y: 155,
        },
        // In Progress
        {
          fillColor: '#eff6ff',
          height: 460,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#93c5fd',
          strokeWidth: 1.5,
          type: 'shape',
          width: 220,
          x: 340,
          y: 100,
        },
        {
          color: '#1d4ed8',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '⏳ En Progreso (Doing)',
          type: 'text',
          width: 190,
          x: 355,
          y: 115,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 90,
          id: uid('stk'),
          text: 'Refactorizar componentes con fondo blanco.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 190,
          x: 355,
          y: 155,
        },
        // Done
        {
          fillColor: '#f0fdf4',
          height: 460,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#86efac',
          strokeWidth: 1.5,
          type: 'shape',
          width: 220,
          x: 580,
          y: 100,
        },
        {
          color: '#15803d',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '✅ Completado (Done)',
          type: 'text',
          width: 190,
          x: 595,
          y: 115,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 90,
          id: uid('stk'),
          text: 'Purga de base de datos y migración inicial.',
          textColor: '#14532d',
          type: 'sticky',
          width: 190,
          x: 595,
          y: 155,
        },
      ];

    case 'tmpl-board-empathy':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '👤 Mapa de Empatía del Usuario',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#f8fafc',
          height: 200,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#38bdf8',
          strokeWidth: 1.5,
          type: 'shape',
          width: 300,
          x: 100,
          y: 100,
        },
        {
          color: '#0284c7',
          fontSize: 14,
          height: 25,
          id: uid('txt'),
          text: '💭 ¿Qué piensa y siente?',
          type: 'text',
          width: 260,
          x: 120,
          y: 115,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Quiere crear diagramas sin distracciones visuales.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 260,
          x: 120,
          y: 160,
        },
        {
          fillColor: '#f8fafc',
          height: 200,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#a855f7',
          strokeWidth: 1.5,
          type: 'shape',
          width: 300,
          x: 430,
          y: 100,
        },
        {
          color: '#7e22ce',
          fontSize: 14,
          height: 25,
          id: uid('txt'),
          text: '👁️ ¿Qué ve?',
          type: 'text',
          width: 260,
          x: 450,
          y: 115,
        },
        {
          color: '#f3e8ff',
          fontSize: 13,
          height: 100,
          id: uid('stk'),
          text: 'Lienzo blanco con puntos tenues y limpios.',
          textColor: '#581c87',
          type: 'sticky',
          width: 260,
          x: 450,
          y: 160,
        },
      ];

    case 'tmpl-board-journey':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🗺️ Customer Journey Map',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        {
          color: '#fef08a',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 1: Descubrimiento\nLlega mediante recomendación o búsqueda.',
          textColor: '#713f12',
          type: 'sticky',
          width: 160,
          x: 100,
          y: 110,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 2: Exploración\nElige una plantilla de pizarrón o documento.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 160,
          x: 290,
          y: 110,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 3: Creación\nTrabaja en un lienzo blanco sin distracciones.',
          textColor: '#14532d',
          type: 'sticky',
          width: 160,
          x: 480,
          y: 110,
        },
        {
          color: '#fed7aa',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Paso 4: Exportación\nDescarga su trabajo listo para compartir.',
          textColor: '#c2410c',
          type: 'sticky',
          width: 160,
          x: 670,
          y: 110,
        },
      ];

    case 'tmpl-board-business':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '📊 Canvas de Modelo de Negocio',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#eff6ff',
          height: 280,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          type: 'shape',
          width: 220,
          x: 350,
          y: 100,
        },
        {
          color: '#1d4ed8',
          fontSize: 15,
          height: 25,
          id: uid('txt'),
          text: '💎 Propuesta de Valor',
          type: 'text',
          width: 190,
          x: 365,
          y: 115,
        },
        {
          color: '#dbeafe',
          fontSize: 13,
          height: 140,
          id: uid('stk'),
          text: 'Herramientas visuales integradas con zona de trabajo blanca y colaboración en tiempo real.',
          textColor: '#1e3a8a',
          type: 'sticky',
          width: 190,
          x: 365,
          y: 160,
        },
      ];

    case 'tmpl-board-matrix':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '⚖️ Matriz de Priorización (Impacto vs Esfuerzo)',
          type: 'text',
          width: 550,
          x: 100,
          y: 40,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 120,
          id: uid('stk'),
          text: '🚀 Quick Win (Alto I / Bajo E):\nEstandarizar fondos blancos en todos los lienzos.',
          textColor: '#14532d',
          type: 'sticky',
          width: 200,
          x: 100,
          y: 110,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 120,
          id: uid('stk'),
          text: '🎯 Estratégico (Alto I / Alto E):\nMotor colaborativo de documentos en tiempo real.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 200,
          x: 330,
          y: 110,
        },
      ];

    case 'tmpl-board-wireframe':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '📱 Bocetos de Interfaz y Wireframes',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#ffffff',
          height: 360,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#64748b',
          strokeWidth: 2,
          type: 'shape',
          width: 260,
          x: 100,
          y: 100,
        },
        {
          color: '#475569',
          fontSize: 14,
          height: 25,
          id: uid('txt'),
          text: '📱 Vista Móvil (Pantalla 1)',
          type: 'text',
          width: 220,
          x: 120,
          y: 120,
        },
      ];

    case 'tmpl-board-roadmap':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🎯 Roadmap Trimestral de Producto',
          type: 'text',
          width: 450,
          x: 100,
          y: 40,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Q1: Suite de Plantillas Blancas\n10 por cada tipo de lienzo.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 170,
          x: 100,
          y: 110,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Q2: Exportación Avanzada\nSoporte vector SVG y PDF editorial.',
          textColor: '#14532d',
          type: 'sticky',
          width: 170,
          x: 300,
          y: 110,
        },
      ];

    case 'tmpl-board-swot':
      return [
        {
          color: '#1e293b',
          fontSize: 24,
          height: 40,
          id: uid('txt'),
          text: '🛡️ Análisis FODA / SWOT',
          type: 'text',
          width: 400,
          x: 100,
          y: 40,
        },
        {
          fillColor: '#f0fdf4',
          height: 220,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#86efac',
          strokeWidth: 2,
          type: 'shape',
          width: 280,
          x: 100,
          y: 100,
        },
        {
          color: '#15803d',
          fontSize: 16,
          height: 25,
          id: uid('txt'),
          text: '💪 Fortalezas',
          type: 'text',
          width: 240,
          x: 120,
          y: 115,
        },
        {
          color: '#bbf7d0',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Diseño limpio y consistente en todos los módulos.',
          textColor: '#14532d',
          type: 'sticky',
          width: 240,
          x: 120,
          y: 160,
        },
        {
          fillColor: '#eff6ff',
          height: 220,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#93c5fd',
          strokeWidth: 2,
          type: 'shape',
          width: 280,
          x: 410,
          y: 100,
        },
        {
          color: '#1d4ed8',
          fontSize: 16,
          height: 25,
          id: uid('txt'),
          text: '🚀 Oportunidades',
          type: 'text',
          width: 240,
          x: 430,
          y: 115,
        },
        {
          color: '#bae6fd',
          fontSize: 13,
          height: 110,
          id: uid('stk'),
          text: 'Adopción acelerada por equipos de diseño y producto.',
          textColor: '#0c4a6e',
          type: 'sticky',
          width: 240,
          x: 430,
          y: 160,
        },
      ];

    default: {
      const preset = ALL_PRESETS.find((p) => p.id === templateId || p.boardTemplateId === templateId);
      if (preset && preset.diagramSubtype) {
        const diagProject = getCustomDiagramProject(preset.id, preset.diagramSubtype, preset.name);
        return convertDiagramToBoardElements(diagProject);
      }
      return [];
    }
  }
}
