import { BoardElement } from '../views/board/board.types.js';

export function getBoardTemplateElements(templateId?: string | null): BoardElement[] {
  if (!templateId) return [];

  const uid = (prefix: string) => `${prefix}_${Math.random().toString(36).substring(2, 9)}`;

  switch (templateId) {
    case 'tmpl-board-retro':
      return [
        {
          color: '#0f172a',
          fontSize: 32,
          fontWeight: 800,
          height: 48,
          id: uid('txt'),
          text: '🚀 Agile Sprint Retrospective',
          type: 'text',
          width: 800,
          x: 100,
          y: 40,
        },
        {
          color: '#64748b',
          fontSize: 16,
          height: 28,
          id: uid('txt'),
          text: 'Sprint 24 Review • Team feedback, key learnings, and committed action items for continuous improvement.',
          type: 'text',
          width: 1000,
          x: 100,
          y: 92,
        },
        {
          fillColor: '#ecfdf5',
          fontSize: 13,
          fontWeight: 700,
          height: 36,
          id: uid('shp'),
          shapeType: 'pill',
          strokeColor: '#10b981',
          strokeWidth: 1.5,
          text: 'Sprint 24 • Completed',
          textColor: '#065f46',
          type: 'shape',
          width: 200,
          x: 1380,
          y: 50,
        },
        // Column 1: What Went Well
        {
          backgroundColor: '#f8fafc',
          borderColor: '#10b981',
          borderWidth: 2,
          height: 720,
          id: uid('sec'),
          title: '🌟 What Went Well',
          titleColor: '#15803d',
          type: 'section',
          width: 440,
          x: 100,
          y: 150,
        },
        {
          color: '#fef08a',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '🚀 Deployment pipeline execution time reduced by 40% after Docker multi-stage caching refactor.',
          textColor: '#854d0e',
          type: 'sticky',
          width: 190,
          x: 120,
          y: 220,
        },
        {
          color: '#dcfce7',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '✅ Zero critical or Sev-1 production regressions reported during the major Auth 2.0 rollout.',
          textColor: '#166534',
          type: 'sticky',
          width: 190,
          x: 330,
          y: 220,
        },
        {
          color: '#e0f2fe',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '🤝 Exceptional async communication between backend and design squads on the new canvas canvas tool.',
          textColor: '#075985',
          type: 'sticky',
          width: 190,
          x: 120,
          y: 380,
        },
        {
          color: '#fef08a',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '⚡ Instant real-time cursor sync passed high-load stress testing with 50+ concurrent contributors.',
          textColor: '#854d0e',
          type: 'sticky',
          width: 190,
          x: 330,
          y: 380,
        },
        // Column 2: Needs Improvement
        {
          backgroundColor: '#f8fafc',
          borderColor: '#f97316',
          borderWidth: 2,
          height: 720,
          id: uid('sec'),
          title: '🔧 Needs Improvement',
          titleColor: '#c2410c',
          type: 'section',
          width: 440,
          x: 580,
          y: 150,
        },
        {
          color: '#ffedd5',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '⏳ Async code reviews lingered idle for over 24 hours due to uneven pull request distribution.',
          textColor: '#9a3412',
          type: 'sticky',
          width: 190,
          x: 600,
          y: 220,
        },
        {
          color: '#ffe4e6',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '⚠️ Staging cluster encountered flaky integration tests during peak hours with database locks.',
          textColor: '#9f1239',
          type: 'sticky',
          width: 190,
          x: 810,
          y: 220,
        },
        {
          color: '#fef3c7',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '📝 Acceptance criteria on several product backlog user stories lacked specific edge-case error copy.',
          textColor: '#92400e',
          type: 'sticky',
          width: 190,
          x: 600,
          y: 380,
        },
        {
          color: '#ffedd5',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '🔔 Too many noisy alerts in Slack #alerts-general channel drowning out actionable notices.',
          textColor: '#9a3412',
          type: 'sticky',
          width: 190,
          x: 810,
          y: 380,
        },
        // Column 3: Action Items
        {
          backgroundColor: '#f8fafc',
          borderColor: '#3b82f6',
          borderWidth: 2,
          height: 720,
          id: uid('sec'),
          title: '🎯 Action Items & Commitments',
          titleColor: '#1d4ed8',
          type: 'section',
          width: 440,
          x: 1060,
          y: 150,
        },
        {
          color: '#e0e7ff',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '👥 Institute scheduled pair-review slots every Tuesday and Thursday at 10:00 AM (Lead: Alex).',
          textColor: '#3730a3',
          type: 'sticky',
          width: 190,
          x: 1080,
          y: 220,
        },
        {
          color: '#ede9fe',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '🤖 Implement automated Slack reminder bot for pull requests pending review past 12h (Lead: Sarah).',
          textColor: '#5b21b6',
          type: 'sticky',
          width: 190,
          x: 1290,
          y: 220,
        },
        {
          color: '#f3e8ff',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '🧪 Isolate and refactor top 5 flakiest integration tests in docker-compose suite (Lead: Marcus).',
          textColor: '#6b21a8',
          type: 'sticky',
          width: 190,
          x: 1080,
          y: 380,
        },
        {
          color: '#e0e7ff',
          fontSize: 15,
          height: 140,
          id: uid('stk'),
          text: '📋 Require completed Acceptance Criteria checklist before moving tickets to In-Progress (Lead: Elena).',
          textColor: '#3730a3',
          type: 'sticky',
          width: 190,
          x: 1290,
          y: 380,
        },
      ];

    case 'tmpl-board-roadmap':
      return [
        {
          color: '#0f172a',
          fontSize: 32,
          fontWeight: 800,
          height: 48,
          id: uid('txt'),
          text: '🗺️ Product & Engineering Strategic Roadmap',
          type: 'text',
          width: 900,
          x: 100,
          y: 40,
        },
        {
          color: '#64748b',
          fontSize: 16,
          height: 28,
          id: uid('txt'),
          text: '2026 Annual Execution Plan • Quarterly delivery tracks, core milestones, and squad allocations.',
          type: 'text',
          width: 1000,
          x: 100,
          y: 92,
        },
        // Q1 Column
        {
          backgroundColor: '#f8fafc',
          borderColor: '#cbd5e1',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: 'Q1 • Core Infrastructure & Auth',
          titleColor: '#334155',
          type: 'section',
          width: 340,
          x: 100,
          y: 150,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#10b981',
          strokeWidth: 2,
          text: 'Multi-Tenant Authentication\nRBAC permissions, session management\nand workspace team isolation.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 120,
          y: 220,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#10b981',
          strokeWidth: 2,
          text: 'High-Performance CRDT Engine\nSub-30ms state sync with conflict-free\nrealtime canvas resolution.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 120,
          y: 370,
        },
        // Q2 Column
        {
          backgroundColor: '#f8fafc',
          borderColor: '#3b82f6',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: 'Q2 • Canvas Studio & Documents',
          titleColor: '#1d4ed8',
          type: 'section',
          width: 340,
          x: 480,
          y: 150,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          text: 'Unified Doc & Canvas Engine\nSeamless transition between text docs,\npresentation decks, and whiteboards.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 500,
          y: 220,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#3b82f6',
          strokeWidth: 2,
          text: 'Offline-First Progressive App\nIndexedDB local persistence cache with\nbackground server synchronization.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 500,
          y: 370,
        },
        // Q3 Column
        {
          backgroundColor: '#f8fafc',
          borderColor: '#8b5cf6',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: 'Q3 • AI Intelligence & Scale',
          titleColor: '#6d28d9',
          type: 'section',
          width: 340,
          x: 860,
          y: 150,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#8b5cf6',
          strokeWidth: 2,
          text: 'AI Canvas Co-Pilot\nSemantic board generation, summary\ninsights and smart diagram layouts.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 880,
          y: 220,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#8b5cf6',
          strokeWidth: 2,
          text: 'Hardware-Accelerated WebGL\nUltra-smooth rendering for boards with\nover 10,000 active vector elements.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 880,
          y: 370,
        },
        // Q4 Column
        {
          backgroundColor: '#f8fafc',
          borderColor: '#cbd5e1',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: 'Q4 • Enterprise Governance',
          titleColor: '#334155',
          type: 'section',
          width: 340,
          x: 1240,
          y: 150,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#64748b',
          strokeWidth: 1.5,
          text: 'Enterprise SAML 2.0 & SCIM\nDirectory sync with Okta, Azure AD\nand automated account offboarding.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 1260,
          y: 220,
        },
        {
          borderRadius: 8,
          fillColor: '#ffffff',
          fontSize: 13,
          height: 130,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#64748b',
          strokeWidth: 1.5,
          text: 'Audit Compliance & DLP\nDetailed immutable audit logs with\ncompliance export guarantees.',
          textColor: '#0f172a',
          type: 'shape',
          width: 300,
          x: 1260,
          y: 370,
        },
      ];

    case 'tmpl-board-journey':
      return [
        {
          color: '#0f172a',
          fontSize: 32,
          fontWeight: 800,
          height: 48,
          id: uid('txt'),
          text: '🧭 Customer Experience & Journey Map',
          type: 'text',
          width: 900,
          x: 100,
          y: 40,
        },
        {
          color: '#64748b',
          fontSize: 16,
          height: 28,
          id: uid('txt'),
          text: 'Holistic mapping of user mindsets, touchpoints, emotion curves, and strategic opportunities across lifecycle.',
          type: 'text',
          width: 1100,
          x: 100,
          y: 92,
        },
        // Persona Profile Section
        {
          backgroundColor: '#ffffff',
          borderColor: '#cbd5e1',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: '👤 Target Persona Profile',
          titleColor: '#0f172a',
          type: 'section',
          width: 320,
          x: 100,
          y: 150,
        },
        {
          borderRadius: 12,
          fillColor: '#eff6ff',
          fontSize: 14,
          height: 160,
          id: uid('shp'),
          shapeType: 'round-rect',
          strokeColor: '#3b82f6',
          strokeWidth: 1.5,
          text: '👩‍💻 Alex Carter\nStaff Systems Architect\n\nGoals: Seamless system diagramming\nand consolidated workspace docs.',
          textColor: '#1e3a8a',
          type: 'shape',
          width: 280,
          x: 120,
          y: 220,
        },
        {
          color: '#fef2f2',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '😤 Core Frustration:\nConstant context-switching across 4 different subscription tools that lack real-time sync.',
          textColor: '#991b1b',
          type: 'sticky',
          width: 280,
          x: 120,
          y: 400,
        },
        {
          color: '#ecfdf5',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '✨ Dream Experience:\nOpen one fast infinite canvas, invite the team with a link, and start collaborating in seconds.',
          textColor: '#065f46',
          type: 'sticky',
          width: 280,
          x: 120,
          y: 570,
        },
        // Phase 1: Discovery
        {
          backgroundColor: '#f8fafc',
          borderColor: '#3b82f6',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: '1. Discovery & Evaluation',
          titleColor: '#1d4ed8',
          type: 'section',
          width: 380,
          x: 460,
          y: 150,
        },
        {
          color: '#fef08a',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '🔍 User Action:\nDiscovers Spriteboard via engineering newsletter. Explores the interactive template gallery.',
          textColor: '#854d0e',
          type: 'sticky',
          width: 340,
          x: 480,
          y: 220,
        },
        {
          color: '#dcfce7',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '💡 Mindset & Sentiment:\nCurious and hopeful. Appreciates the instant responsive web performance and zero-clutter UI.',
          textColor: '#166534',
          type: 'sticky',
          width: 340,
          x: 480,
          y: 390,
        },
        {
          color: '#fff1f2',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '⚠️ Friction Point:\nWants immediate certainty that board data can be exported in clean SVG and JSON formats.',
          textColor: '#9f1239',
          type: 'sticky',
          width: 340,
          x: 480,
          y: 560,
        },
        // Phase 2: Onboarding
        {
          backgroundColor: '#f8fafc',
          borderColor: '#8b5cf6',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: '2. First Creation & Onboarding',
          titleColor: '#6d28d9',
          type: 'section',
          width: 380,
          x: 880,
          y: 150,
        },
        {
          color: '#ede9fe',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '🎨 User Action:\nClicks "Use Template" on Sprint Retro. Customizes initial sticky notes in under 60 seconds.',
          textColor: '#5b21b6',
          type: 'sticky',
          width: 340,
          x: 900,
          y: 220,
        },
        {
          color: '#dcfce7',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '🤩 Mindset & Sentiment:\nDelighted by fluid 60fps pan and zoom controls, snapping guides, and keyboard ergonomics.',
          textColor: '#166534',
          type: 'sticky',
          width: 900,
          x: 900,
          y: 390,
        },
        {
          color: '#e0f2fe',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '🚀 Opportunity:\nPrompt one-click squad invite modal immediately after first canvas milestone is created.',
          textColor: '#075985',
          type: 'sticky',
          width: 340,
          x: 900,
          y: 560,
        },
        // Phase 3: Team Expansion
        {
          backgroundColor: '#f8fafc',
          borderColor: '#10b981',
          borderWidth: 1.5,
          height: 720,
          id: uid('sec'),
          title: '3. Team Expansion & Advocacy',
          titleColor: '#15803d',
          type: 'section',
          width: 380,
          x: 1300,
          y: 150,
        },
        {
          color: '#dcfce7',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '👥 User Action:\nShares room link in Slack. 6 engineers join concurrently with live cursor presence.',
          textColor: '#166534',
          type: 'sticky',
          width: 340,
          x: 1320,
          y: 220,
        },
        {
          color: '#fef08a',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '🏆 Mindset & Sentiment:\nHigh confidence. Alex becomes champion and initiates team upgrade to Business tier.',
          textColor: '#854d0e',
          type: 'sticky',
          width: 340,
          x: 1320,
          y: 390,
        },
        {
          color: '#e0e7ff',
          fontSize: 14,
          height: 150,
          id: uid('stk'),
          text: '💡 Next Goal:\nPublish the team\'s internal sprint templates to the company workspace library.',
          textColor: '#3730a3',
          type: 'sticky',
          width: 340,
          x: 1320,
          y: 560,
        },
      ];

    default:
      return [];
  }
}
