import { ShapeType } from './board-shapes.config.js';
import { STICKY_NOTE_PRESETS } from './sticky-notes.config.js';

export interface DiagramComponentItem {
  category: 'flowchart' | 'mindmap' | 'cloud_data' | 'structure' | 'connectors' | 'stickies';
  categoryLabel: string;
  connectorStyle?: 'curved' | 'orthogonal' | 'straight';
  description: string;
  fillColor?: string;
  height?: number;
  id: string;
  isMindMapNode?: boolean;
  name: string;
  previewSvg: string;
  shapeType?: ShapeType;
  strokeColor?: string;
  strokeStyle?: 'dashed' | 'dotted' | 'solid';
  text?: string;
  textColor?: string;
  type: 'shape' | 'connector' | 'sticky';
  width?: number;
}

export const DIAGRAM_COMPONENTS: DiagramComponentItem[] = [
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Punto de inicio o fin del proceso',
    fillColor: '#ecfdf5',
    height: 48,
    id: 'flow_start_end',
    name: 'Inicio / Fin',
    previewSvg: '<rect x="4" y="14" width="40" height="20" rx="10" ry="10" fill="#ecfdf5" stroke="#10b981" stroke-width="2.5" /><text x="24" y="27" font-size="7.5" font-family="sans-serif" font-weight="600" fill="#065f46" text-anchor="middle">Inicio</text>',
    shapeType: 'pill',
    strokeColor: '#10b981',
    text: 'Inicio / Fin',
    textColor: '#065f46',
    type: 'shape',
    width: 140,
  },
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Paso, acción u operación',
    fillColor: '#eff6ff',
    height: 60,
    id: 'flow_process',
    name: 'Proceso',
    previewSvg: '<rect x="5" y="10" width="38" height="28" rx="3" ry="3" fill="#eff6ff" stroke="#3b82f6" stroke-width="2.5" /><text x="24" y="27" font-size="7.5" font-family="sans-serif" font-weight="600" fill="#1e40af" text-anchor="middle">Proceso</text>',
    shapeType: 'rect',
    strokeColor: '#3b82f6',
    text: 'Proceso',
    textColor: '#1e40af',
    type: 'shape',
    width: 140,
  },
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Evaluación condicional Sí / No',
    fillColor: '#fffbeb',
    height: 80,
    id: 'flow_decision',
    name: 'Decisión',
    previewSvg: '<polygon points="24,6 43,24 24,42 5,24" fill="#fffbeb" stroke="#f59e0b" stroke-width="2.5" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#92400e" text-anchor="middle">¿Decisión?</text>',
    shapeType: 'diamond',
    strokeColor: '#f59e0b',
    text: '¿Decisión?',
    textColor: '#92400e',
    type: 'shape',
    width: 130,
  },
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Entrada o salida de información',
    fillColor: '#f5f3ff',
    height: 60,
    id: 'flow_io',
    name: 'Entrada / Salida',
    previewSvg: '<polygon points="12,10 43,10 36,38 5,38" fill="#f5f3ff" stroke="#8b5cf6" stroke-width="2.5" /><text x="24" y="27" font-size="7" font-family="sans-serif" font-weight="600" fill="#5b21b6" text-anchor="middle">Datos I/O</text>',
    shapeType: 'parallelogram',
    strokeColor: '#8b5cf6',
    text: 'Entrada / Salida',
    textColor: '#5b21b6',
    type: 'shape',
    width: 140,
  },
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Almacén o tabla de base de datos',
    fillColor: '#ecfeff',
    height: 75,
    id: 'flow_database',
    name: 'Base de Datos',
    previewSvg: '<path d="M10,12 C10,7 38,7 38,12 L38,36 C38,41 10,41 10,36 Z" fill="#ecfeff" stroke="#06b6d4" stroke-width="2.5" /><path d="M10,12 C10,17 38,17 38,12" fill="none" stroke="#06b6d4" stroke-width="2.5" /><path d="M10,24 C10,29 38,29 38,24" fill="none" stroke="#06b6d4" stroke-width="2.5" />',
    shapeType: 'cylinder',
    strokeColor: '#06b6d4',
    text: 'Base de Datos',
    textColor: '#155e75',
    type: 'shape',
    width: 120,
  },
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Documento o salida impresa',
    fillColor: '#f8fafc',
    height: 70,
    id: 'flow_document',
    name: 'Documento',
    previewSvg: '<path d="M10,8 L32,8 L38,14 L38,38 C34,35 30,41 24,38 C18,35 14,41 10,38 Z" fill="#f8fafc" stroke="#64748b" stroke-width="2.5" /><text x="24" y="26" font-size="6.5" font-family="sans-serif" font-weight="600" fill="#334155" text-anchor="middle">Doc</text>',
    shapeType: 'document',
    strokeColor: '#64748b',
    text: 'Documento',
    textColor: '#334155',
    type: 'shape',
    width: 130,
  },
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Servicio en la nube o API externa',
    fillColor: '#f0f9ff',
    height: 75,
    id: 'flow_cloud',
    name: 'Cloud / API',
    previewSvg: '<path d="M14,32 C10,32 7,29 8,24 C6,19 13,14 19,16 C23,10 33,11 35,18 C40,19 41,27 36,32 Z" fill="#f0f9ff" stroke="#0284c7" stroke-width="2.5" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#075985" text-anchor="middle">Cloud</text>',
    shapeType: 'cloud',
    strokeColor: '#0284c7',
    text: 'Cloud / API',
    textColor: '#075985',
    type: 'shape',
    width: 140,
  },
  {
    category: 'flowchart',
    categoryLabel: 'Diagramas de Flujo',
    description: 'Conector de flujo entre páginas o bloques',
    fillColor: '#fdf2f8',
    height: 50,
    id: 'flow_circle',
    name: 'Conector de Página',
    previewSvg: '<circle cx="24" cy="24" r="16" fill="#fdf2f8" stroke="#db2777" stroke-width="2.5" /><text x="24" y="27" font-size="8" font-family="sans-serif" font-weight="700" fill="#9d174d" text-anchor="middle">A</text>',
    shapeType: 'circle',
    strokeColor: '#db2777',
    text: 'A',
    textColor: '#9d174d',
    type: 'shape',
    width: 50,
  },
  {
    category: 'mindmap',
    categoryLabel: 'Mapas Mentales & Conceptuales',
    description: 'Nodo raíz o idea principal',
    fillColor: '#e0e7ff',
    height: 56,
    id: 'mm_central_node',
    isMindMapNode: true,
    name: 'Idea Central',
    previewSvg: '<rect x="4" y="11" width="40" height="26" rx="8" ry="8" fill="#e0e7ff" stroke="#6366f1" stroke-width="2.5" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="700" fill="#3730a3" text-anchor="middle">Idea Central</text>',
    shapeType: 'round-rect',
    strokeColor: '#6366f1',
    text: 'Idea Central',
    textColor: '#3730a3',
    type: 'shape',
    width: 150,
  },
  {
    category: 'mindmap',
    categoryLabel: 'Mapas Mentales & Conceptuales',
    description: 'Rama o subtema secundario azul',
    fillColor: '#dbeafe',
    height: 44,
    id: 'mm_branch_blue',
    isMindMapNode: true,
    name: 'Rama Azul',
    previewSvg: '<rect x="5" y="14" width="38" height="20" rx="10" ry="10" fill="#dbeafe" stroke="#3b82f6" stroke-width="2" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#1e40af" text-anchor="middle">Subtema</text>',
    shapeType: 'pill',
    strokeColor: '#3b82f6',
    text: 'Subtema Azul',
    textColor: '#1e40af',
    type: 'shape',
    width: 130,
  },
  {
    category: 'mindmap',
    categoryLabel: 'Mapas Mentales & Conceptuales',
    description: 'Rama o subtema secundario verde',
    fillColor: '#d1fae5',
    height: 44,
    id: 'mm_branch_emerald',
    isMindMapNode: true,
    name: 'Rama Verde',
    previewSvg: '<rect x="5" y="14" width="38" height="20" rx="10" ry="10" fill="#d1fae5" stroke="#10b981" stroke-width="2" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#065f46" text-anchor="middle">Subtema</text>',
    shapeType: 'pill',
    strokeColor: '#10b981',
    text: 'Subtema Verde',
    textColor: '#065f46',
    type: 'shape',
    width: 130,
  },
  {
    category: 'mindmap',
    categoryLabel: 'Mapas Mentales & Conceptuales',
    description: 'Rama o subtema secundario naranja',
    fillColor: '#ffedd5',
    height: 44,
    id: 'mm_branch_amber',
    isMindMapNode: true,
    name: 'Rama Naranja',
    previewSvg: '<rect x="5" y="14" width="38" height="20" rx="10" ry="10" fill="#ffedd5" stroke="#f97316" stroke-width="2" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#9a3412" text-anchor="middle">Subtema</text>',
    shapeType: 'pill',
    strokeColor: '#f97316',
    text: 'Subtema Naranja',
    textColor: '#9a3412',
    type: 'shape',
    width: 130,
  },
  {
    category: 'mindmap',
    categoryLabel: 'Mapas Mentales & Conceptuales',
    description: 'Rama o subtema secundario morado',
    fillColor: '#f3e8ff',
    height: 44,
    id: 'mm_branch_purple',
    isMindMapNode: true,
    name: 'Rama Morada',
    previewSvg: '<rect x="5" y="14" width="38" height="20" rx="10" ry="10" fill="#f3e8ff" stroke="#a855f7" stroke-width="2" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#6b21a8" text-anchor="middle">Subtema</text>',
    shapeType: 'pill',
    strokeColor: '#a855f7',
    text: 'Subtema Morado',
    textColor: '#6b21a8',
    type: 'shape',
    width: 130,
  },
  {
    category: 'mindmap',
    categoryLabel: 'Mapas Mentales & Conceptuales',
    description: 'Rama o subtema secundario rosa',
    fillColor: '#ffe4e6',
    height: 44,
    id: 'mm_branch_rose',
    isMindMapNode: true,
    name: 'Rama Rosa',
    previewSvg: '<rect x="5" y="14" width="38" height="20" rx="10" ry="10" fill="#ffe4e6" stroke="#f43f5e" stroke-width="2" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#9f1239" text-anchor="middle">Subtema</text>',
    shapeType: 'pill',
    strokeColor: '#f43f5e',
    text: 'Subtema Rosa',
    textColor: '#9f1239',
    type: 'shape',
    width: 130,
  },
  {
    category: 'mindmap',
    categoryLabel: 'Mapas Mentales & Conceptuales',
    description: 'Caja conceptual con frase de enlace',
    fillColor: '#f0fdfa',
    height: 42,
    id: 'mm_concept_node',
    isMindMapNode: true,
    name: 'Concepto Enlazado',
    previewSvg: '<rect x="5" y="12" width="38" height="24" rx="4" ry="4" fill="#f0fdfa" stroke="#0d9488" stroke-width="2" /><text x="24" y="26" font-size="6.5" font-family="sans-serif" font-weight="600" fill="#115e59" text-anchor="middle">Concepto</text>',
    shapeType: 'round-rect',
    strokeColor: '#0d9488',
    text: 'Concepto Clave',
    textColor: '#115e59',
    type: 'shape',
    width: 140,
  },
  {
    category: 'cloud_data',
    categoryLabel: 'Arquitectura Cloud & Infra',
    description: 'Base de datos relacional SQL o NoSQL',
    fillColor: '#ecfeff',
    height: 75,
    id: 'arch_db_sql',
    name: 'Base de Datos SQL',
    previewSvg: '<path d="M10,12 C10,7 38,7 38,12 L38,36 C38,41 10,41 10,36 Z" fill="#ecfeff" stroke="#0891b2" stroke-width="2.5" /><path d="M10,12 C10,17 38,17 38,12" fill="none" stroke="#0891b2" stroke-width="2.5" /><path d="M10,24 C10,29 38,29 38,24" fill="none" stroke="#0891b2" stroke-width="2.5" />',
    shapeType: 'cylinder',
    strokeColor: '#0891b2',
    text: 'PostgreSQL / MySQL',
    textColor: '#155e75',
    type: 'shape',
    width: 130,
  },
  {
    category: 'cloud_data',
    categoryLabel: 'Arquitectura Cloud & Infra',
    description: 'Servidor web, host o API Gateway',
    fillColor: '#eff6ff',
    height: 60,
    id: 'arch_server_host',
    name: 'Servidor / Gateway',
    previewSvg: '<rect x="6" y="10" width="36" height="28" rx="3" ry="3" fill="#eff6ff" stroke="#2563eb" stroke-width="2.5" /><line x1="12" y1="18" x2="24" y2="18" stroke="#2563eb" stroke-width="2" /><circle cx="34" cy="18" r="2" fill="#10b981" /><line x1="12" y1="28" x2="24" y2="28" stroke="#2563eb" stroke-width="2" /><circle cx="34" cy="28" r="2" fill="#10b981" />',
    shapeType: 'round-rect',
    strokeColor: '#2563eb',
    text: 'API Server / Backend',
    textColor: '#1e40af',
    type: 'shape',
    width: 140,
  },
  {
    category: 'cloud_data',
    categoryLabel: 'Arquitectura Cloud & Infra',
    description: 'Servicio en la nube, AWS, GCP o Azure',
    fillColor: '#f0f9ff',
    height: 75,
    id: 'arch_cloud_service',
    name: 'Microservicio Cloud',
    previewSvg: '<path d="M14,32 C10,32 7,29 8,24 C6,19 13,14 19,16 C23,10 33,11 35,18 C40,19 41,27 36,32 Z" fill="#f0f9ff" stroke="#0284c7" stroke-width="2.5" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#075985" text-anchor="middle">AWS/GCP</text>',
    shapeType: 'cloud',
    strokeColor: '#0284c7',
    text: 'Microservicio / Cloud',
    textColor: '#075985',
    type: 'shape',
    width: 140,
  },
  {
    category: 'cloud_data',
    categoryLabel: 'Arquitectura Cloud & Infra',
    description: 'Almacenamiento de archivos S3 / Bucket',
    fillColor: '#f8fafc',
    height: 70,
    id: 'arch_storage_s3',
    name: 'Storage de Archivos',
    previewSvg: '<path d="M10,8 L32,8 L38,14 L38,38 C34,35 30,41 24,38 C18,35 14,41 10,38 Z" fill="#f8fafc" stroke="#64748b" stroke-width="2.5" /><text x="24" y="26" font-size="6.5" font-family="sans-serif" font-weight="600" fill="#334155" text-anchor="middle">S3</text>',
    shapeType: 'document',
    strokeColor: '#64748b',
    text: 'S3 / Object Storage',
    textColor: '#334155',
    type: 'shape',
    width: 130,
  },
  {
    category: 'cloud_data',
    categoryLabel: 'Arquitectura Cloud & Infra',
    description: 'Cola de mensajes RabbitMQ / Kafka / Redis',
    fillColor: '#faf5ff',
    height: 55,
    id: 'arch_queue_bus',
    name: 'Cola de Mensajes',
    previewSvg: '<polygon points="10,12 40,12 34,36 4,36" fill="#faf5ff" stroke="#9333ea" stroke-width="2.5" /><text x="22" y="26" font-size="6.5" font-family="sans-serif" font-weight="600" fill="#6b21a8" text-anchor="middle">Kafka/Queue</text>',
    shapeType: 'parallelogram',
    strokeColor: '#9333ea',
    text: 'Event Bus / Queue',
    textColor: '#6b21a8',
    type: 'shape',
    width: 140,
  },
  {
    category: 'cloud_data',
    categoryLabel: 'Arquitectura Cloud & Infra',
    description: 'Firewall, Seguridad & Autenticación',
    fillColor: '#ecfdf5',
    height: 75,
    id: 'arch_security_auth',
    name: 'Auth & Seguridad',
    previewSvg: '<polygon points="24,6 43,24 24,42 5,24" fill="#ecfdf5" stroke="#059669" stroke-width="2.5" /><text x="24" y="26" font-size="6.5" font-family="sans-serif" font-weight="600" fill="#065f46" text-anchor="middle">Auth/2FA</text>',
    shapeType: 'diamond',
    strokeColor: '#059669',
    text: 'Auth / Security',
    textColor: '#065f46',
    type: 'shape',
    width: 130,
  },
  {
    category: 'structure',
    categoryLabel: 'Estructura & Organización',
    description: 'Dirección General o CEO corporativo',
    fillColor: '#e0e7ff',
    height: 52,
    id: 'org_director_role',
    name: 'Dirección General',
    previewSvg: '<rect x="6" y="12" width="36" height="24" rx="6" ry="6" fill="#e0e7ff" stroke="#4f46e5" stroke-width="2.5" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="700" fill="#3730a3" text-anchor="middle">Dirección</text>',
    shapeType: 'round-rect',
    strokeColor: '#4f46e5',
    text: 'Dirección General (CEO)',
    textColor: '#3730a3',
    type: 'shape',
    width: 160,
  },
  {
    category: 'structure',
    categoryLabel: 'Estructura & Organización',
    description: 'Dirección de departamento o área',
    fillColor: '#eff6ff',
    height: 48,
    id: 'org_area_role',
    name: 'Dirección de Área',
    previewSvg: '<rect x="6" y="12" width="36" height="24" rx="4" ry="4" fill="#eff6ff" stroke="#0284c7" stroke-width="2" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#0369a1" text-anchor="middle">Área</text>',
    shapeType: 'round-rect',
    strokeColor: '#0284c7',
    text: 'Dirección de Tecnología (CTO)',
    textColor: '#0369a1',
    type: 'shape',
    width: 150,
  },
  {
    category: 'structure',
    categoryLabel: 'Estructura & Organización',
    description: 'Líder de equipo o squad ágil',
    fillColor: '#ecfdf5',
    height: 46,
    id: 'org_lead_role',
    name: 'Líder de Equipo',
    previewSvg: '<rect x="6" y="12" width="36" height="24" rx="4" ry="4" fill="#ecfdf5" stroke="#10b981" stroke-width="2" /><text x="24" y="26" font-size="7" font-family="sans-serif" font-weight="600" fill="#065f46" text-anchor="middle">Líder</text>',
    shapeType: 'round-rect',
    strokeColor: '#10b981',
    text: 'Líder de Desarrollo',
    textColor: '#065f46',
    type: 'shape',
    width: 145,
  },
  {
    category: 'structure',
    categoryLabel: 'Estructura & Organización',
    description: 'Integrante especialista o rol operativo',
    fillColor: '#fff7ed',
    height: 42,
    id: 'org_member_role',
    name: 'Especialista',
    previewSvg: '<rect x="5" y="14" width="38" height="20" rx="10" ry="10" fill="#fff7ed" stroke="#f97316" stroke-width="2" /><text x="24" y="26" font-size="6.5" font-family="sans-serif" font-weight="600" fill="#9a3412" text-anchor="middle">Especialista</text>',
    shapeType: 'pill',
    strokeColor: '#f97316',
    text: 'Especialista / Ingeniero',
    textColor: '#9a3412',
    type: 'shape',
    width: 140,
  },
  {
    category: 'structure',
    categoryLabel: 'Estructura & Organización',
    description: 'Hito o entregable cronológico',
    fillColor: '#f3e8ff',
    height: 44,
    id: 'org_milestone_badge',
    name: 'Hito de Roadmap',
    previewSvg: '<rect x="5" y="14" width="38" height="20" rx="10" ry="10" fill="#f3e8ff" stroke="#8b5cf6" stroke-width="2" /><text x="24" y="26" font-size="6.5" font-family="sans-serif" font-weight="600" fill="#5b21b6" text-anchor="middle">Hito / Sprint</text>',
    shapeType: 'pill',
    strokeColor: '#8b5cf6',
    text: 'Hito 1: Lanzamiento MVP',
    textColor: '#5b21b6',
    type: 'shape',
    width: 150,
  },
  {
    category: 'connectors',
    categoryLabel: 'Conectores & Flechas',
    connectorStyle: 'curved',
    description: 'Línea curva orgánica con flecha direccional',
    id: 'conn_curved',
    name: 'Conector Curvo',
    previewSvg: '<path d="M8,36 C16,12 30,36 40,12" fill="none" stroke="#6366f1" stroke-width="3" stroke-linecap="round"/><polygon points="34,10 42,12 39,19" fill="#6366f1"/>',
    type: 'connector',
  },
  {
    category: 'connectors',
    categoryLabel: 'Conectores & Flechas',
    connectorStyle: 'orthogonal',
    description: 'Línea con codos a 90° y flecha direccional',
    id: 'conn_orthogonal',
    name: 'Conector Ortogonal',
    previewSvg: '<path d="M8,36 L24,36 L24,14 L40,14" fill="none" stroke="#3b82f6" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><polygon points="34,9 42,14 34,19" fill="#3b82f6"/>',
    type: 'connector',
  },
  {
    category: 'connectors',
    categoryLabel: 'Conectores & Flechas',
    connectorStyle: 'straight',
    description: 'Línea recta directa con flecha direccional',
    id: 'conn_straight',
    name: 'Conector Recto',
    previewSvg: '<line x1="8" y1="38" x2="38" y2="10" stroke="#10b981" stroke-width="3" stroke-linecap="round"/><polygon points="31,8 40,10 38,19" fill="#10b981"/>',
    type: 'connector',
  },
  ...STICKY_NOTE_PRESETS.map((s) => ({
    category: 'stickies' as const,
    categoryLabel: 'Notas Adhesivas',
    description: `Nota adhesiva ${s.name.toLowerCase()}`,
    fillColor: s.color,
    id: `stk_${s.id.replace('sticky_', '')}`,
    name: `Nota ${s.name}`,
    previewSvg: `<rect x="8" y="8" width="32" height="32" rx="4" ry="4" fill="${s.color}" stroke="${s.stroke}" stroke-width="1.5"/><line x1="14" y1="18" x2="30" y2="18" stroke="${s.textColor}" stroke-width="2" stroke-linecap="round"/><line x1="14" y1="24" x2="26" y2="24" stroke="${s.textColor}" stroke-width="2" stroke-linecap="round"/>`,
    textColor: s.textColor,
    type: 'sticky' as const,
  })),
];
