import { PresentationSlideItem } from '../types/presentation.types.js';
import { BoardElement } from '../views/board/board.types.js';

export function getPresentationTemplateSlides(templateId?: string | null): PresentationSlideItem[] {
  if (!templateId) return [];

  const uid = (prefix: string) => `${prefix}_${Math.random().toString(36).substring(2, 9)}`;

  switch (templateId) {
    case 'tmpl-pres-pitch':
      return [
        {
          background: { color: '#0f172a', type: 'solid' },
          createdAt: Date.now(),
          elements: [
            {
              borderRadius: 20,
              fillColor: '#1e293b',
              fontSize: 14,
              fontWeight: 700,
              height: 38,
              id: uid('shp'),
              shapeType: 'pill',
              strokeColor: '#38bdf8',
              strokeWidth: 1.5,
              text: 'SEED ROUND PITCH DECK • RAISING $3.5M',
              textColor: '#38bdf8',
              type: 'shape',
              width: 380,
              x: 100,
              y: 120,
            },
            {
              color: '#ffffff',
              fontSize: 48,
              fontWeight: 800,
              height: 120,
              id: uid('txt'),
              text: 'The Real-Time Visual Workspace\nfor Fast-Moving Engineering Teams',
              type: 'text',
              width: 1050,
              x: 100,
              y: 180,
            },
            {
              color: '#94a3b8',
              fontSize: 20,
              height: 40,
              id: uid('txt'),
              text: 'Unifying whiteboards, interactive documentation, and slide presentations into one lightning-fast canvas.',
              type: 'text',
              width: 1000,
              x: 100,
              y: 330,
            },
            {
              borderRadius: 12,
              fillColor: '#1e293b',
              fontSize: 16,
              height: 140,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#334155',
              strokeWidth: 1,
              text: '🚀 $2.4M ARR\n140% YoY Net Growth\nHigh Enterprise Retention',
              textColor: '#f8fafc',
              type: 'shape',
              width: 320,
              x: 100,
              y: 430,
            },
            {
              borderRadius: 12,
              fillColor: '#1e293b',
              fontSize: 16,
              height: 140,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#334155',
              strokeWidth: 1,
              text: '👥 85,000+ Teams\nActive weekly developers\nand design architects',
              textColor: '#f8fafc',
              type: 'shape',
              width: 320,
              x: 460,
              y: 430,
            },
            {
              borderRadius: 12,
              fillColor: '#1e293b',
              fontSize: 16,
              height: 140,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#334155',
              strokeWidth: 1,
              text: '⚡ < 30ms Sync SLA\nCRDT state reconciliation\nwith zero merge conflicts',
              textColor: '#f8fafc',
              type: 'shape',
              width: 320,
              x: 820,
              y: 430,
            },
          ],
          id: 'slide-1',
          name: '1. Vision & Overview',
        },
        {
          background: { color: '#0f172a', type: 'solid' },
          createdAt: Date.now() + 100,
          elements: [
            {
              color: '#38bdf8',
              fontSize: 16,
              fontWeight: 700,
              height: 28,
              id: uid('txt'),
              text: 'THE PROBLEM & OUR SOLUTION',
              type: 'text',
              width: 600,
              x: 100,
              y: 80,
            },
            {
              color: '#ffffff',
              fontSize: 40,
              fontWeight: 800,
              height: 60,
              id: uid('txt'),
              text: 'Why Teams Love Spriteboard',
              type: 'text',
              width: 900,
              x: 100,
              y: 120,
            },
            {
              borderRadius: 16,
              fillColor: '#1e293b',
              fontSize: 16,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#ef4444',
              strokeWidth: 1.5,
              text: '❌ The Traditional Nightmare\n\n• Fragmented tools: Jira + Miro + Confluence + Slides\n• Stale, out-of-sync architecture diagrams\n• Cumbersome permission silos across teams\n• Sluggish performance on large boards',
              textColor: '#fca5a5',
              type: 'shape',
              width: 500,
              x: 100,
              y: 210,
            },
            {
              borderRadius: 16,
              fillColor: '#1e293b',
              fontSize: 16,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#10b981',
              strokeWidth: 1.5,
              text: '✨ The Spriteboard Advantage\n\n• Single unified canvas: Sketch, write, present\n• Real-time multiplayer with live cursors\n• Community & team template marketplace\n• Blazing fast 60fps canvas engine',
              textColor: '#86efac',
              type: 'shape',
              width: 500,
              x: 640,
              y: 210,
            },
          ],
          id: 'slide-2',
          name: '2. Problem & Solution',
        },
        {
          background: { color: '#0f172a', type: 'solid' },
          createdAt: Date.now() + 200,
          elements: [
            {
              color: '#38bdf8',
              fontSize: 16,
              fontWeight: 700,
              height: 28,
              id: uid('txt'),
              text: 'MARKET OPPORTUNITY & BUSINESS MODEL',
              type: 'text',
              width: 600,
              x: 100,
              y: 80,
            },
            {
              color: '#ffffff',
              fontSize: 40,
              fontWeight: 800,
              height: 60,
              id: uid('txt'),
              text: 'Massive Market with Proven Flywheel',
              type: 'text',
              width: 900,
              x: 100,
              y: 120,
            },
            {
              borderRadius: 12,
              fillColor: '#1e293b',
              fontSize: 16,
              height: 180,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#6366f1',
              strokeWidth: 1.5,
              text: '🎯 Product-Led Growth\n\nIndividual creators design and share templates for free.\nColleagues join as viewers, then convert into paid editors.',
              textColor: '#e0e7ff',
              type: 'shape',
              width: 500,
              x: 100,
              y: 220,
            },
            {
              borderRadius: 12,
              fillColor: '#1e293b',
              fontSize: 16,
              height: 180,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#38bdf8',
              strokeWidth: 1.5,
              text: '💼 Enterprise Tier\n\n$18/user/month with SSO SAML 2.0, audit logs,\nunlimited team template libraries, and priority SLA support.',
              textColor: '#e0f2fe',
              type: 'shape',
              width: 500,
              x: 640,
              y: 220,
            },
            {
              borderRadius: 12,
              fillColor: '#064e3b',
              fontSize: 18,
              fontWeight: 700,
              height: 80,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#10b981',
              strokeWidth: 2,
              text: '🤝 Raising $3.5M Seed • 18 Months Runway to $10M ARR',
              textColor: '#ecfdf5',
              type: 'shape',
              width: 1040,
              x: 100,
              y: 440,
            },
          ],
          id: 'slide-3',
          name: '3. Traction & Funding',
        },
      ];

    case 'tmpl-pres-qbr':
      return [
        {
          background: { color: '#ffffff', type: 'solid' },
          createdAt: Date.now(),
          elements: [
            {
              borderRadius: 18,
              fillColor: '#e0e7ff',
              fontSize: 13,
              fontWeight: 700,
              height: 36,
              id: uid('shp'),
              shapeType: 'pill',
              strokeColor: '#4f46e5',
              strokeWidth: 1,
              text: 'Q3 EXECUTIVE PERFORMANCE REVIEW',
              textColor: '#4338ca',
              type: 'shape',
              width: 320,
              x: 100,
              y: 110,
            },
            {
              color: '#0f172a',
              fontSize: 48,
              fontWeight: 800,
              height: 64,
              id: uid('txt'),
              text: 'Quarterly Business Review',
              type: 'text',
              width: 800,
              x: 100,
              y: 165,
            },
            {
              color: '#64748b',
              fontSize: 20,
              height: 32,
              id: uid('txt'),
              text: 'Executive results, key OKR achievement, and guidance for upcoming Q4 growth.',
              type: 'text',
              width: 900,
              x: 100,
              y: 240,
            },
            {
              borderRadius: 12,
              fillColor: '#f8fafc',
              fontSize: 16,
              height: 160,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#e2e8f0',
              strokeWidth: 1.5,
              text: '💰 $4.85M Revenue\nTarget: $4.20M\n+15.4% Overachievement',
              textColor: '#0f172a',
              type: 'shape',
              width: 320,
              x: 100,
              y: 350,
            },
            {
              borderRadius: 12,
              fillColor: '#f8fafc',
              fontSize: 16,
              height: 160,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#e2e8f0',
              strokeWidth: 1.5,
              text: '📈 128.5% NDR\nNet Dollar Retention\nTop-quartile SaaS benchmark',
              textColor: '#0f172a',
              type: 'shape',
              width: 320,
              x: 460,
              y: 350,
            },
            {
              borderRadius: 12,
              fillColor: '#f8fafc',
              fontSize: 16,
              height: 160,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#e2e8f0',
              strokeWidth: 1.5,
              text: '⭐ +74.2 NPS\nCustomer Satisfaction\n+8.2 points QoQ increase',
              textColor: '#0f172a',
              type: 'shape',
              width: 320,
              x: 820,
              y: 350,
            },
          ],
          id: 'slide-1',
          name: '1. Executive Summary',
        },
        {
          background: { color: '#ffffff', type: 'solid' },
          createdAt: Date.now() + 100,
          elements: [
            {
              color: '#4f46e5',
              fontSize: 16,
              fontWeight: 700,
              height: 28,
              id: uid('txt'),
              text: 'PRODUCT & PLATFORM MILESTONES',
              type: 'text',
              width: 600,
              x: 100,
              y: 80,
            },
            {
              color: '#0f172a',
              fontSize: 40,
              fontWeight: 800,
              height: 60,
              id: uid('txt'),
              text: 'Q3 Delivery Accomplishments',
              type: 'text',
              width: 800,
              x: 100,
              y: 120,
            },
            {
              borderRadius: 12,
              fillColor: '#f0fdf4',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#86efac',
              strokeWidth: 1.5,
              text: '🚀 High-Impact Launches\n\n• Unified Canvas Suite: Single workspace for docs and boards.\n• Template Marketplace: System and team publishing pipeline.\n• Zero-downtime MySQL + Redis clustering deployment.\n• Enterprise permission roles (Admin, Editor, Viewer).',
              textColor: '#14532d',
              type: 'shape',
              width: 500,
              x: 100,
              y: 200,
            },
            {
              borderRadius: 12,
              fillColor: '#eff6ff',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#93c5fd',
              strokeWidth: 1.5,
              text: '📊 Key Efficiency Gains\n\n• Server CPU utilization reduced by 38%.\n• WebSocket connection setup latency cut in half.\n• Customer onboarding completion rate jumped to 82%.\n• 99.98% platform uptime achieved across the quarter.',
              textColor: '#1e3a8a',
              type: 'shape',
              width: 500,
              x: 640,
              y: 200,
            },
          ],
          id: 'slide-2',
          name: '2. Product Milestones',
        },
        {
          background: { color: '#ffffff', type: 'solid' },
          createdAt: Date.now() + 200,
          elements: [
            {
              color: '#4f46e5',
              fontSize: 16,
              fontWeight: 700,
              height: 28,
              id: uid('txt'),
              text: 'LOOKING FORWARD: Q4 GOALS',
              type: 'text',
              width: 600,
              x: 100,
              y: 80,
            },
            {
              color: '#0f172a',
              fontSize: 40,
              fontWeight: 800,
              height: 60,
              id: uid('txt'),
              text: 'Q4 Strategic Priorities',
              type: 'text',
              width: 800,
              x: 100,
              y: 120,
            },
            {
              borderRadius: 12,
              fillColor: '#f8fafc',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#3b82f6',
              strokeWidth: 1.5,
              text: '🎯 1. Enterprise Expansion\n\n• Complete SOC2 Type II audit compliance.\n• Roll out SAML 2.0 with Okta & Azure AD.\n• Target: 40 net new enterprise contracts.',
              textColor: '#1e293b',
              type: 'shape',
              width: 320,
              x: 100,
              y: 200,
            },
            {
              borderRadius: 12,
              fillColor: '#f8fafc',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#8b5cf6',
              strokeWidth: 1.5,
              text: '🤖 2. AI Intelligence\n\n• Smart canvas generation with Gemini.\n• Automated meeting synthesis to board.\n• Target: 50,000 monthly AI queries.',
              textColor: '#1e293b',
              type: 'shape',
              width: 320,
              x: 460,
              y: 200,
            },
            {
              borderRadius: 12,
              fillColor: '#f8fafc',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#10b981',
              strokeWidth: 1.5,
              text: '🌍 3. Global Edge Network\n\n• Deploy EU and APAC WebSocket gateways.\n• Achieve global < 20ms sync latency.\n• Target: 99.99% multi-region uptime.',
              textColor: '#1e293b',
              type: 'shape',
              width: 320,
              x: 820,
              y: 200,
            },
          ],
          id: 'slide-3',
          name: '3. Strategic Guidance',
        },
      ];

    case 'tmpl-pres-launch':
      return [
        {
          background: { color: '#090d16', type: 'solid' },
          createdAt: Date.now(),
          elements: [
            {
              borderRadius: 18,
              fillColor: '#064e3b',
              fontSize: 13,
              fontWeight: 700,
              height: 36,
              id: uid('shp'),
              shapeType: 'pill',
              strokeColor: '#10b981',
              strokeWidth: 1,
              text: 'PRODUCT LAUNCH • SPRITEBOARD STUDIO 2.0',
              textColor: '#34d399',
              type: 'shape',
              width: 380,
              x: 100,
              y: 110,
            },
            {
              color: '#ffffff',
              fontSize: 50,
              fontWeight: 800,
              height: 120,
              id: uid('txt'),
              text: 'Introducing Spriteboard\nStudio 2.0',
              type: 'text',
              width: 900,
              x: 100,
              y: 170,
            },
            {
              color: '#9ca3af',
              fontSize: 20,
              height: 32,
              id: uid('txt'),
              text: 'The distributed visual platform that empowers engineering teams to build at lightspeed.',
              type: 'text',
              width: 1000,
              x: 100,
              y: 310,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 15,
              height: 160,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#1f2937',
              strokeWidth: 1.5,
              text: '⚡ Instant Collaboration\nZero friction room join\nwith real-time multiplayer',
              textColor: '#f9fafb',
              type: 'shape',
              width: 320,
              x: 100,
              y: 390,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 15,
              height: 160,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#1f2937',
              strokeWidth: 1.5,
              text: '📐 Unified Canvases\nWhiteboards, slides and docs\nunder one consistent engine',
              textColor: '#f9fafb',
              type: 'shape',
              width: 320,
              x: 460,
              y: 390,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 15,
              height: 160,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#1f2937',
              strokeWidth: 1.5,
              text: '🛡️ Enterprise Security\nFull data sovereignty with\nRBAC and encrypted storage',
              textColor: '#f9fafb',
              type: 'shape',
              width: 320,
              x: 820,
              y: 390,
            },
          ],
          id: 'slide-1',
          name: '1. Launch Announcement',
        },
        {
          background: { color: '#090d16', type: 'solid' },
          createdAt: Date.now() + 100,
          elements: [
            {
              color: '#34d399',
              fontSize: 16,
              fontWeight: 700,
              height: 28,
              id: uid('txt'),
              text: 'DISTRIBUTED ARCHITECTURE',
              type: 'text',
              width: 600,
              x: 100,
              y: 80,
            },
            {
              color: '#ffffff',
              fontSize: 40,
              fontWeight: 800,
              height: 60,
              id: uid('txt'),
              text: 'Built for Scale and Zero-Latency',
              type: 'text',
              width: 800,
              x: 100,
              y: 120,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#0284c7',
              strokeWidth: 1.5,
              text: '🖥️ Client Engine\n\n• HTML5 2D Vector Canvas\n• 60fps pan, zoom & drag snappiness\n• IndexedDB offline caching\n• Sub-pixel crisp rendering',
              textColor: '#e0f2fe',
              type: 'shape',
              width: 320,
              x: 100,
              y: 200,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#7c3aed',
              strokeWidth: 1.5,
              text: '🔄 Real-Time Mesh\n\n• Edge WebSocket connection pool\n• Redis Pub/Sub broadcast bus\n• Delta compression with binary packing\n• Peer presence and heartbeat',
              textColor: '#ede9fe',
              type: 'shape',
              width: 320,
              x: 460,
              y: 200,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 15,
              height: 380,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#059669',
              strokeWidth: 1.5,
              text: '💾 Cloud Storage\n\n• MySQL 8 persistent store\n• S3 asset and thumbnail pipeline\n• Snapshot history versioning\n• Multi-tenant team isolation',
              textColor: '#dcfce7',
              type: 'shape',
              width: 320,
              x: 820,
              y: 200,
            },
          ],
          id: 'slide-2',
          name: '2. Architecture Overview',
        },
        {
          background: { color: '#090d16', type: 'solid' },
          createdAt: Date.now() + 200,
          elements: [
            {
              color: '#34d399',
              fontSize: 16,
              fontWeight: 700,
              height: 28,
              id: uid('txt'),
              text: 'GLOBAL AVAILABILITY',
              type: 'text',
              width: 600,
              x: 100,
              y: 80,
            },
            {
              color: '#ffffff',
              fontSize: 40,
              fontWeight: 800,
              height: 60,
              id: uid('txt'),
              text: 'Deployment Timeline & Rollout',
              type: 'text',
              width: 800,
              x: 100,
              y: 120,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 16,
              height: 180,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#10b981',
              strokeWidth: 1.5,
              text: '🚀 Phase 1: Private Beta (October 2026)\n\nInviting top 50 engineering organizations to test studio features.\nDedicated engineering Slack channel with direct bug reporting.',
              textColor: '#dcfce7',
              type: 'shape',
              width: 1040,
              x: 100,
              y: 210,
            },
            {
              borderRadius: 12,
              fillColor: '#111827',
              fontSize: 16,
              height: 180,
              id: uid('shp'),
              shapeType: 'round-rect',
              strokeColor: '#38bdf8',
              strokeWidth: 1.5,
              text: '🌍 Phase 2: General Availability (November 2026)\n\nGlobal rollout across US, Europe, and Asia regions.\nPublic release of Community Template Sharing and verified creator badges.',
              textColor: '#e0f2fe',
              type: 'shape',
              width: 1040,
              x: 100,
              y: 420,
            },
          ],
          id: 'slide-3',
          name: '3. Rollout Timeline',
        },
      ];

    default:
      return [];
  }
}
