export interface PresetVariant {
  height: number;
  imagePath?: string;
  label: string;
  width: number;
}

export interface PresetItem {
  aspectType: 'compact' | 'large' | 'square' | 'standard' | 'tall' | 'wide';
  boardTemplateId?: string;
  canvasType?: 'board' | 'doc';
  categoryKey: string;
  categoryName: string;
  diagramSubtype?: string;
  diagramTemplateId?: string;
  docTemplateId?: string;
  height: number;
  id: string;
  imagePath: string;
  isTemplate: boolean;
  masterPath?: string;
  name: string;
  pixelTemplateId?: string;
  tags?: string[];
  variants?: PresetVariant[];
  width: number;
}

export const ALL_PRESETS: PresetItem[] = [
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-brainstorm',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-brainstorm',
    imagePath: '/assets/templates/boards/brainstorm.svg',
    isTemplate: true,
    name: 'Lluvia de Ideas y Notas',
    tags: ['pizarra', 'board', 'whiteboard', 'ideas', 'notas', 'brainstorm'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-retro',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-retro',
    imagePath: '/assets/templates/boards/retro.svg',
    isTemplate: true,
    name: 'Retrospectiva Ágil de Equipo',
    tags: ['retrospectiva', 'retro', 'agile', 'scrum', 'pizarra', 'equipo'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-kanban',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-kanban',
    imagePath: '/assets/templates/boards/kanban.svg',
    isTemplate: true,
    name: 'Tablero Kanban de Tareas',
    tags: ['kanban', 'tareas', 'sprint', 'flujo', 'pizarra', 'agile'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-empathy',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-empathy',
    imagePath: '/assets/templates/boards/empathy.svg',
    isTemplate: true,
    name: 'Mapa de Empatía del Usuario',
    tags: ['empatia', 'usuario', 'ux', 'diseño', 'investigacion', 'pizarra'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-journey',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-journey',
    imagePath: '/assets/templates/boards/journey.svg',
    isTemplate: true,
    name: 'Customer Journey Map',
    tags: ['journey', 'cliente', 'experiencia', 'fases', 'pizarra', 'ux'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-business',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-business',
    imagePath: '/assets/templates/boards/business.svg',
    isTemplate: true,
    name: 'Canvas de Modelo de Negocio',
    tags: ['business', 'negocio', 'canvas', 'propuesta de valor', 'pizarra'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-matrix',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-matrix',
    imagePath: '/assets/templates/boards/matrix.svg',
    isTemplate: true,
    name: 'Matriz Impacto vs Esfuerzo',
    tags: ['matriz', 'priorizacion', 'impacto', 'esfuerzo', 'quick wins', 'pizarra'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-wireframe',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-wireframe',
    imagePath: '/assets/templates/boards/wireframe.svg',
    isTemplate: true,
    name: 'Muro de Bocetos y Wireframes',
    tags: ['wireframe', 'ui', 'diseño', 'pantallas', 'mockup', 'pizarra'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-roadmap',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-roadmap',
    imagePath: '/assets/templates/boards/roadmap.svg',
    isTemplate: true,
    name: 'Roadmap Trimestral Visual',
    tags: ['roadmap', 'trimestre', 'metas', 'planificacion', 'pizarra'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    boardTemplateId: 'tmpl-board-swot',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 1080,
    id: 'tmpl-board-swot',
    imagePath: '/assets/templates/boards/swot.svg',
    isTemplate: true,
    name: 'Análisis FODA Colaborativo',
    tags: ['foda', 'swot', 'estrategia', 'fortalezas', 'debilidades', 'pizarra'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-1',
    imagePath: '/assets/templates/mindmaps/mindmap_1.svg',
    isTemplate: true,
    name: 'Lluvia de Ideas de Innovación',
    tags: ['mapa mental', 'mindmap', 'innovacion', 'ideas', 'brainstorming'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-2',
    imagePath: '/assets/templates/mindmaps/mindmap_2.svg',
    isTemplate: true,
    name: 'Planificación Estratégica',
    tags: ['mapa mental', 'mindmap', 'estrategia', 'planificacion', 'metas'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-3',
    imagePath: '/assets/templates/mindmaps/mindmap_3.svg',
    isTemplate: true,
    name: 'Estructura de Conocimiento',
    tags: ['mapa mental', 'mindmap', 'estudio', 'conocimiento', 'aprendizaje'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-4',
    imagePath: '/assets/templates/mindmaps/mindmap_4.svg',
    isTemplate: true,
    name: 'Lanzamiento de Producto',
    tags: ['mapa mental', 'mindmap', 'producto', 'launch', 'marketing'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-5',
    imagePath: '/assets/templates/mindmaps/mindmap_5.svg',
    isTemplate: true,
    name: 'Análisis de Causa y Soluciones',
    tags: ['mapa mental', 'mindmap', 'problemas', 'soluciones', 'analisis'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-6',
    imagePath: '/assets/templates/mindmaps/mindmap_6.svg',
    isTemplate: true,
    name: 'Objetivos y Hábitos Personales',
    tags: ['mapa mental', 'mindmap', 'habitos', 'objetivos', 'desarrollo'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-7',
    imagePath: '/assets/templates/mindmaps/mindmap_7.svg',
    isTemplate: true,
    name: 'Estrategia de Marketing de Contenidos',
    tags: ['mapa mental', 'mindmap', 'marketing', 'contenidos', 'redes'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-8',
    imagePath: '/assets/templates/mindmaps/mindmap_8.svg',
    isTemplate: true,
    name: 'Arquitectura de Información Web',
    tags: ['mapa mental', 'mindmap', 'ux', 'arquitectura', 'web', 'sitemap'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-9',
    imagePath: '/assets/templates/mindmaps/mindmap_9.svg',
    isTemplate: true,
    name: 'Metodología de Investigación',
    tags: ['mapa mental', 'mindmap', 'tesis', 'investigacion', 'ciencia'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'mindmap',
    height: 1080,
    id: 'tmpl-mind-10',
    imagePath: '/assets/templates/mindmaps/mindmap_10.svg',
    isTemplate: true,
    name: 'Síntesis y Resumen de Libro',
    tags: ['mapa mental', 'mindmap', 'resumen', 'libro', 'educacion'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-1',
    imagePath: '/assets/templates/conceptmaps/conceptmap_1.svg',
    isTemplate: true,
    name: 'Redes y Computación',
    tags: ['mapa conceptual', 'concept map', 'redes', 'informatica', 'tecnologia'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-2',
    imagePath: '/assets/templates/conceptmaps/conceptmap_2.svg',
    isTemplate: true,
    name: 'Metodologías Ágiles y Scrum',
    tags: ['mapa conceptual', 'concept map', 'agile', 'scrum', 'gestion'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-3',
    imagePath: '/assets/templates/conceptmaps/conceptmap_3.svg',
    isTemplate: true,
    name: 'Ecosistemas y Biología',
    tags: ['mapa conceptual', 'concept map', 'biologia', 'ecosistemas', 'ciencia'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-4',
    imagePath: '/assets/templates/conceptmaps/conceptmap_4.svg',
    isTemplate: true,
    name: 'Inteligencia Artificial y ML',
    tags: ['mapa conceptual', 'concept map', 'ia', 'machine learning', 'datos'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-5',
    imagePath: '/assets/templates/conceptmaps/conceptmap_5.svg',
    isTemplate: true,
    name: 'Mercados Financieros y Economía',
    tags: ['mapa conceptual', 'concept map', 'finanzas', 'economia', 'mercados'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-6',
    imagePath: '/assets/templates/conceptmaps/conceptmap_6.svg',
    isTemplate: true,
    name: 'Anatomía del Sistema Nervioso',
    tags: ['mapa conceptual', 'concept map', 'medicina', 'salud', 'anatomia'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-7',
    imagePath: '/assets/templates/conceptmaps/conceptmap_7.svg',
    isTemplate: true,
    name: 'Filosofía y Corrientes de Pensamiento',
    tags: ['mapa conceptual', 'concept map', 'filosofia', 'pensamiento', 'logica'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-8',
    imagePath: '/assets/templates/conceptmaps/conceptmap_8.svg',
    isTemplate: true,
    name: 'Estructuras de Datos y Algoritmos',
    tags: ['mapa conceptual', 'concept map', 'programacion', 'algoritmos', 'dsa'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-9',
    imagePath: '/assets/templates/conceptmaps/conceptmap_9.svg',
    isTemplate: true,
    name: 'Teoría de la Comunicación Humana',
    tags: ['mapa conceptual', 'concept map', 'comunicacion', 'lenguaje', 'medios'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'conceptmap',
    height: 1080,
    id: 'tmpl-concept-10',
    imagePath: '/assets/templates/conceptmaps/conceptmap_10.svg',
    isTemplate: true,
    name: 'Mecánica Clásica y Dinámica',
    tags: ['mapa conceptual', 'concept map', 'fisica', 'mecanica', 'ciencia'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-1',
    imagePath: '/assets/templates/flowcharts/flowchart_1.svg',
    isTemplate: true,
    name: 'Registro y Autenticación de Usuario',
    tags: ['flujo', 'flowchart', 'autenticacion', 'seguridad', 'proceso'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-2',
    imagePath: '/assets/templates/flowcharts/flowchart_2.svg',
    isTemplate: true,
    name: 'Flujo de Pasarela de Pagos y Checkout',
    tags: ['flujo', 'flowchart', 'checkout', 'pagos', 'ecommerce'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-3',
    imagePath: '/assets/templates/flowcharts/flowchart_3.svg',
    isTemplate: true,
    name: 'Gestión de Tickets de Soporte',
    tags: ['flujo', 'flowchart', 'soporte', 'tickets', 'atencion'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-4',
    imagePath: '/assets/templates/flowcharts/flowchart_4.svg',
    isTemplate: true,
    name: 'Pipeline CI/CD y Despliegue',
    tags: ['flujo', 'flowchart', 'devops', 'cicd', 'deploy'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-5',
    imagePath: '/assets/templates/flowcharts/flowchart_5.svg',
    isTemplate: true,
    name: 'Proceso de Selección de Personal',
    tags: ['flujo', 'flowchart', 'rrhh', 'hiring', 'entrevistas'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-6',
    imagePath: '/assets/templates/flowcharts/flowchart_6.svg',
    isTemplate: true,
    name: 'Canalización de Datos (ETL)',
    tags: ['flujo', 'flowchart', 'datos', 'etl', 'pipeline'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-7',
    imagePath: '/assets/templates/flowcharts/flowchart_7.svg',
    isTemplate: true,
    name: 'Flujo de Aprobación de Compras',
    tags: ['flujo', 'flowchart', 'compras', 'finanzas', 'aprobacion'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-8',
    imagePath: '/assets/templates/flowcharts/flowchart_8.svg',
    isTemplate: true,
    name: 'Algoritmo de Decisión y Ordenamiento',
    tags: ['flujo', 'flowchart', 'algoritmo', 'logica', 'software'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-9',
    imagePath: '/assets/templates/flowcharts/flowchart_9.svg',
    isTemplate: true,
    name: 'Control de Calidad y Pruebas QA',
    tags: ['flujo', 'flowchart', 'qa', 'testing', 'calidad'],
    width: 1920,
  },
  {
    aspectType: 'wide',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    diagramSubtype: 'flowchart',
    height: 1080,
    id: 'tmpl-flow-10',
    imagePath: '/assets/templates/flowcharts/flowchart_10.svg',
    isTemplate: true,
    name: 'Devoluciones y Garantías E-Commerce',
    tags: ['flujo', 'flowchart', 'garantia', 'devolucion', 'soporte'],
    width: 1920,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'blank',
    height: 1056,
    id: 'tmpl-doc-1',
    imagePath: '/assets/templates/docs/doc_1.svg',
    isTemplate: true,
    name: 'Documento en blanco',
    tags: ['documento', 'doc', 'blanco', 'texto', 'notas'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'business_report',
    height: 1056,
    id: 'tmpl-doc-2',
    imagePath: '/assets/templates/docs/doc_2.svg',
    isTemplate: true,
    name: 'Informe Ejecutivo Corporativo',
    tags: ['documento', 'doc', 'informe', 'reporte', 'corporativo'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'formal_letter',
    height: 1056,
    id: 'tmpl-doc-3',
    imagePath: '/assets/templates/docs/doc_3.svg',
    isTemplate: true,
    name: 'Carta Formal',
    tags: ['documento', 'doc', 'carta', 'comunicacion', 'formal'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'meeting_minutes',
    height: 1056,
    id: 'tmpl-doc-4',
    imagePath: '/assets/templates/docs/doc_4.svg',
    isTemplate: true,
    name: 'Minuta de Reunión y Acuerdos',
    tags: ['documento', 'doc', 'minuta', 'reunion', 'acuerdos'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'resume_cv',
    height: 1056,
    id: 'tmpl-doc-5',
    imagePath: '/assets/templates/docs/doc_5.svg',
    isTemplate: true,
    name: 'Currículum Vitae (CV Profesional)',
    tags: ['documento', 'doc', 'cv', 'curriculum', 'empleo'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'project_proposal',
    height: 1056,
    id: 'tmpl-doc-6',
    imagePath: '/assets/templates/docs/doc_6.svg',
    isTemplate: true,
    name: 'Propuesta Comercial y Cotización',
    tags: ['documento', 'doc', 'propuesta', 'comercial', 'ventas'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'software_spec',
    height: 1056,
    id: 'tmpl-doc-7',
    imagePath: '/assets/templates/docs/doc_7.svg',
    isTemplate: true,
    name: 'Especificación de Software (SRS)',
    tags: ['documento', 'doc', 'srs', 'software', 'tecnico'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'company_policy',
    height: 1056,
    id: 'tmpl-doc-8',
    imagePath: '/assets/templates/docs/doc_8.svg',
    isTemplate: true,
    name: 'Manual de Políticas y Normativas',
    tags: ['documento', 'doc', 'politicas', 'normas', 'manual'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'service_contract',
    height: 1056,
    id: 'tmpl-doc-9',
    imagePath: '/assets/templates/docs/doc_9.svg',
    isTemplate: true,
    name: 'Contrato de Prestación de Servicios',
    tags: ['documento', 'doc', 'contrato', 'legal', 'servicios'],
    width: 816,
  },
  {
    aspectType: 'standard',
    canvasType: 'doc',
    categoryKey: 'doc',
    categoryName: 'Documentos',
    docTemplateId: 'internal_newsletter',
    height: 1056,
    id: 'tmpl-doc-10',
    imagePath: '/assets/templates/docs/doc_10.svg',
    isTemplate: true,
    name: 'Boletín Informativo Interno',
    tags: ['documento', 'doc', 'boletin', 'newsletter', 'comunicacion'],
    width: 816,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 32,
    id: 'tmpl-pixel-1',
    imagePath: '/assets/templates/pixels/pixel_1.svg',
    isTemplate: true,
    name: 'Caballero Héroe 32×32',
    pixelTemplateId: 'hero',
    tags: ['pixel', 'sprite', 'caballero', 'heroe', 'rpg', 'personaje'],
    width: 32,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 32,
    id: 'tmpl-pixel-2',
    imagePath: '/assets/templates/pixels/pixel_2.svg',
    isTemplate: true,
    name: 'Pociones Mágicas 32×32',
    pixelTemplateId: 'potions',
    tags: ['pixel', 'pociones', 'magia', 'items', 'rpg'],
    width: 32,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 16,
    id: 'tmpl-pixel-3',
    imagePath: '/assets/templates/pixels/pixel_3.svg',
    isTemplate: true,
    name: 'Monedas y Gemas Retro 16×16',
    pixelTemplateId: 'coins',
    tags: ['pixel', 'monedas', 'oro', 'gemas', 'retro', 'items'],
    width: 16,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 32,
    id: 'tmpl-pixel-4',
    imagePath: '/assets/templates/pixels/pixel_4.svg',
    isTemplate: true,
    name: 'Espadas Legendarias 32×32',
    pixelTemplateId: 'weapons',
    tags: ['pixel', 'espadas', 'armas', 'fantasia', 'rpg'],
    width: 32,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 32,
    id: 'tmpl-pixel-5',
    imagePath: '/assets/templates/pixels/pixel_5.svg',
    isTemplate: true,
    name: 'Monstruito Slime 32×32',
    pixelTemplateId: 'creature',
    tags: ['pixel', 'slime', 'monstruo', 'enemigo', 'rpg'],
    width: 32,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 32,
    id: 'tmpl-pixel-6',
    imagePath: '/assets/templates/pixels/pixel_6.svg',
    isTemplate: true,
    name: 'Tiles de Mazmorra 32×32',
    pixelTemplateId: 'tiles',
    tags: ['pixel', 'tiles', 'mazmorra', 'escenario', 'pared'],
    width: 32,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 64,
    id: 'tmpl-pixel-7',
    imagePath: '/assets/templates/pixels/pixel_7.svg',
    isTemplate: true,
    name: 'Árboles y Naturaleza 64×64',
    pixelTemplateId: 'plants',
    tags: ['pixel', 'arbol', 'naturaleza', 'bosque', 'escenario'],
    width: 64,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 16,
    id: 'tmpl-pixel-8',
    imagePath: '/assets/templates/pixels/pixel_8.svg',
    isTemplate: true,
    name: 'Corazones de Vida 16×16',
    pixelTemplateId: 'hearts',
    tags: ['pixel', 'corazon', 'vida', 'ui', 'hud', 'salud'],
    width: 16,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 32,
    id: 'tmpl-pixel-9',
    imagePath: '/assets/templates/pixels/pixel_9.svg',
    isTemplate: true,
    name: 'Nave Arcade Espacial 32×32',
    pixelTemplateId: 'vehicle',
    tags: ['pixel', 'nave', 'arcade', 'espacio', 'scifi'],
    width: 32,
  },
  {
    aspectType: 'square',
    canvasType: 'board',
    categoryKey: 'board',
    categoryName: 'Pizarrón',
    height: 16,
    id: 'tmpl-pixel-10',
    imagePath: '/assets/templates/pixels/pixel_10.svg',
    isTemplate: true,
    name: 'Iconos y Glifos UI 16×16',
    pixelTemplateId: 'ui',
    tags: ['pixel', 'iconos', 'glifos', 'interfaz', 'hud'],
    width: 16,
  },
];
