import { DocFontFamily } from './doc-fonts.config.js';

export const DOC_FONTS_EXTENDED_CATALOG: DocFontFamily[] = [
  {
    category: 'handwriting',
    fallback: 'cursive',
    family: 'Sacramento',
    googleFont: 'Sacramento',
    id: 'sacramento',
    isPopular: false,
    name: 'Sacramento',
    tags: ['handwriting', 'cursiva', 'delicada', 'caligrafica', 'femenina', 'suave'],
    variants: [
      { name: 'Regular', style: 'normal', weight: 400 },
    ],
  },
  {
    category: 'handwriting',
    fallback: 'cursive',
    family: 'Satisfy',
    googleFont: 'Satisfy',
    id: 'satisfy',
    isPopular: false,
    name: 'Satisfy',
    tags: ['handwriting', 'cursiva', 'brush', 'pincel', 'casual'],
    variants: [
      { name: 'Regular', style: 'normal', weight: 400 },
    ],
  },
  {
    category: 'handwriting',
    fallback: 'cursive',
    family: 'Alex Brush',
    googleFont: 'Alex+Brush',
    id: 'alex-brush',
    isPopular: false,
    name: 'Alex Brush',
    tags: ['handwriting', 'cursiva', 'caligrafica', 'elegante', 'clasica'],
    variants: [
      { name: 'Regular', style: 'normal', weight: 400 },
    ],
  },
  {
    category: 'display',
    fallback: 'cursive, sans-serif',
    family: 'Lobster',
    googleFont: 'Lobster',
    id: 'lobster',
    isPopular: true,
    name: 'Lobster',
    tags: ['display', 'letrero', 'vintage', 'retro', 'titular', 'cursiva', 'restaurante'],
    variants: [
      { name: 'Regular', style: 'normal', weight: 400 },
    ],
  },
  {
    category: 'display',
    fallback: 'serif',
    family: 'Abril Fatface',
    googleFont: 'Abril+Fatface',
    id: 'abril-fatface',
    isPopular: true,
    name: 'Abril Fatface',
    tags: ['display', 'letrero', 'titular', 'didone', 'moda', 'elegante', 'impacto'],
    variants: [
      { name: 'Regular', style: 'normal', weight: 400 },
    ],
  },
  {
    category: 'display',
    fallback: 'sans-serif',
    family: 'Righteous',
    googleFont: 'Righteous',
    id: 'righteous',
    isPopular: false,
    name: 'Righteous',
    tags: ['display', 'letrero', 'retro', 'moderna', 'futurista', 'poster'],
    variants: [
      { name: 'Regular', style: 'normal', weight: 400 },
    ],
  },
  {
    category: 'display',
    fallback: 'sans-serif',
    family: 'Bungee',
    googleFont: 'Bungee',
    id: 'bungee',
    isPopular: false,
    name: 'Bungee',
    tags: ['display', 'letrero', 'urbana', 'bloque', 'impacto', 'cartel'],
    variants: [
      { name: 'Regular', style: 'normal', weight: 400 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'Raleway',
    googleFont: 'Raleway:ital,wght@0,100..900;1,100..900',
    id: 'raleway',
    isPopular: true,
    name: 'Raleway',
    tags: ['modern', 'sans', 'elegante', 'fina', 'diseno', 'canva'],
    variants: [
      { name: 'Ultradelgada', style: 'normal', weight: 100 },
      { name: 'Muy delgada', style: 'normal', weight: 200 },
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Extranegrita', style: 'normal', weight: 800 },
      { name: 'Ultragruesa', style: 'normal', weight: 900 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'Plus Jakarta Sans',
    googleFont: 'Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800',
    id: 'plus-jakarta-sans',
    isPopular: true,
    name: 'Plus Jakarta Sans',
    tags: ['modern', 'sans', 'tech', 'startup', 'futurista', 'limpia'],
    variants: [
      { name: 'Muy delgada', style: 'normal', weight: 200 },
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Extranegrita', style: 'normal', weight: 800 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'DM Sans',
    googleFont: 'DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000',
    id: 'dm-sans',
    isPopular: true,
    name: 'DM Sans',
    tags: ['modern', 'sans', 'geometrica', 'editorial', 'canva'],
    variants: [
      { name: 'Ultradelgada', style: 'normal', weight: 100 },
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Ultragruesa', style: 'normal', weight: 900 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'Outfit',
    googleFont: 'Outfit:wght@100..900',
    id: 'outfit',
    isPopular: false,
    name: 'Outfit',
    tags: ['modern', 'sans', 'geometrica', 'fresca', 'brillante'],
    variants: [
      { name: 'Ultradelgada', style: 'normal', weight: 100 },
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Ultragruesa', style: 'normal', weight: 900 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'Space Grotesk',
    googleFont: 'Space+Grotesk:wght@300..700',
    id: 'space-grotesk',
    isPopular: false,
    name: 'Space Grotesk',
    tags: ['modern', 'sans', 'tech', 'brutalismo', 'espacio', 'mono-inspired'],
    variants: [
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'Quicksand',
    googleFont: 'Quicksand:wght@300..700',
    id: 'quicksand',
    isPopular: true,
    name: 'Quicksand',
    tags: ['modern', 'sans', 'redondeada', 'suave', 'amigable', 'infantil'],
    variants: [
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'Comfortaa',
    googleFont: 'Comfortaa:wght@300..700',
    id: 'comfortaa',
    isPopular: false,
    name: 'Comfortaa',
    tags: ['modern', 'sans', 'redondeada', 'curva', 'diseño', 'logo'],
    variants: [
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
    ],
  },
  {
    category: 'modern',
    fallback: 'sans-serif',
    family: 'Rubik',
    googleFont: 'Rubik:ital,wght@0,300..900;1,300..900',
    id: 'rubik',
    isPopular: false,
    name: 'Rubik',
    tags: ['modern', 'sans', 'suave', 'esquinas-redondeadas', 'ui'],
    variants: [
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Extranegrita', style: 'normal', weight: 800 },
      { name: 'Ultragruesa', style: 'normal', weight: 900 },
    ],
  },
  {
    category: 'monospace',
    fallback: 'monospace',
    family: 'Fira Code',
    googleFont: 'Fira+Code:wght@300..700',
    id: 'fira-code',
    isPopular: true,
    name: 'Fira Code',
    tags: ['monospace', 'codigo', 'programacion', 'terminal', 'ligaduras'],
    variants: [
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
    ],
  },
  {
    category: 'monospace',
    fallback: 'monospace',
    family: 'JetBrains Mono',
    googleFont: 'JetBrains+Mono:ital,wght@0,100..800;1,100..800',
    id: 'jetbrains-mono',
    isPopular: true,
    name: 'JetBrains Mono',
    tags: ['monospace', 'codigo', 'desarrollador', 'legible'],
    variants: [
      { name: 'Ultradelgada', style: 'normal', weight: 100 },
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Media', style: 'normal', weight: 500 },
      { name: 'Seminegrita', style: 'normal', weight: 600 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Extranegrita', style: 'normal', weight: 800 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
    ],
  },
  {
    category: 'monospace',
    fallback: 'monospace',
    family: 'Inconsolata',
    googleFont: 'Inconsolata:wght@200..900',
    id: 'inconsolata',
    isPopular: false,
    name: 'Inconsolata',
    tags: ['monospace', 'consola', 'limpia', 'codigo'],
    variants: [
      { name: 'Delgada', style: 'normal', weight: 300 },
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Ultragruesa', style: 'normal', weight: 900 },
    ],
  },
  {
    category: 'sans-serif',
    fallback: 'Helvetica, Arial, sans-serif',
    family: 'Arial',
    id: 'arial',
    isPopular: true,
    name: 'Arial',
    tags: ['sans', 'sistema', 'estandar', 'universal', 'office'],
    variants: [
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
      { name: 'Negrita Cursiva', style: 'italic', weight: 700 },
    ],
  },
  {
    category: 'serif',
    fallback: 'Times, serif',
    family: 'Times New Roman',
    id: 'times-new-roman',
    isPopular: true,
    name: 'Times New Roman',
    tags: ['serif', 'sistema', 'academico', 'oficial', 'formal', 'documento'],
    variants: [
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
      { name: 'Negrita Cursiva', style: 'italic', weight: 700 },
    ],
  },
  {
    category: 'serif',
    fallback: 'serif',
    family: 'Georgia',
    id: 'georgia',
    isPopular: true,
    name: 'Georgia',
    tags: ['serif', 'sistema', 'editorial', 'lectura-web', 'elegante'],
    variants: [
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
      { name: 'Negrita Cursiva', style: 'italic', weight: 700 },
    ],
  },
  {
    category: 'monospace',
    fallback: 'Courier, monospace',
    family: 'Courier New',
    id: 'courier-new',
    isPopular: false,
    name: 'Courier New',
    tags: ['monospace', 'sistema', 'maquina-escribir', 'antigua'],
    variants: [
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
    ],
  },
  {
    category: 'sans-serif',
    fallback: 'sans-serif',
    family: 'Verdana',
    id: 'verdana',
    isPopular: false,
    name: 'Verdana',
    tags: ['sans', 'sistema', 'ancha', 'legible'],
    variants: [
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Negrita', style: 'normal', weight: 700 },
      { name: 'Cursiva', style: 'italic', weight: 400 },
    ],
  },
  {
    category: 'bold',
    fallback: 'sans-serif',
    family: 'Impact',
    id: 'impact',
    isPopular: false,
    name: 'Impact',
    tags: ['bold', 'display', 'sistema', 'impacto', 'gruesa', 'meme'],
    variants: [
      { name: 'Regular (Ultra Negrita)', style: 'normal', weight: 700 },
    ],
  },
  {
    category: 'handwriting',
    fallback: 'cursive, sans-serif',
    family: 'Comic Sans MS',
    id: 'comic-sans-ms',
    isPopular: false,
    name: 'Comic Sans MS',
    tags: ['handwriting', 'sistema', 'casual', 'infantil', 'comic'],
    variants: [
      { name: 'Normal', style: 'normal', weight: 400 },
      { name: 'Negrita', style: 'normal', weight: 700 },
    ],
  },
];
